import { BiomeDef } from '@/types/game';

export const BIOME_DEFS: BiomeDef[] = [
  {
    id: 'topsoil',
    name: 'การเดินทางใต้พิภพตามความลึก (Dynamic)',
    enName: 'Dynamic Subterranean Strata',
    desc: 'เปลี่ยนโทนสีและบรรยากาศฉากหลังโดยอัตโนมัติตามความลึกและการเติบโตของราก',
    enDesc: 'Canvas background dynamically transitions through underground strata as roots grow deeper',
    icon: '🧭',
    bgGradient: 'radial-gradient(ellipse at 50% 20%, #201a14 0%, #15100c 60%, #0d0a08 100%)',
    particleType: 'leaves',
    particleColor: 'rgba(143, 209, 122, 0.4)',
    ambientBonusDesc: 'ฉากหลังเปลี่ยนโทนสีตามชั้นความลึก 0m - 10,000m+ อัตโนมัติ',
    enAmbientBonusDesc: 'Adapts background dynamically across strata from 0m to 10,000m+',
    relicRequiredCount: 0,
  },
  {
    id: 'myco_abyss',
    name: 'หุบเหวเห็ดราเรืองแสง',
    enName: 'Bioluminescent Myco Abyss',
    desc: 'หุบเหวลึกที่ส่องสว่างด้วยละอองสปอร์ชีวภาพของไมคอร์ไรซา',
    enDesc: 'A luminous subterranean chasm bathed in glowing mycorrhizal spores',
    icon: '🍄',
    bgGradient: 'radial-gradient(ellipse at 50% 30%, #152218 0%, #0d160f 60%, #060a07 100%)',
    particleType: 'spores',
    particleColor: 'rgba(74, 222, 128, 0.5)',
    ambientBonusDesc: '+25% โบนัสจากเครือข่ายราก (Synergies)',
    enAmbientBonusDesc: '+25% Mycorrhizal Network Synergy Bonus',
    relicRequiredCount: 2,
  },
  {
    id: 'crystal_caverns',
    name: 'ถ้ำผลึกคริสตัลใต้พิภพ',
    enName: 'Subterranean Crystal Caverns',
    desc: 'ถ้ำที่ประดับด้วยผลึกแร่สะท้อนแสงหลากสีระยิบระยับ',
    enDesc: 'Prismatic cavern walls encrusted with shimmering telluric geode crystals',
    icon: '💎',
    bgGradient: 'radial-gradient(ellipse at 50% 30%, #12202b 0%, #0b151e 60%, #050a0f 100%)',
    particleType: 'crystals',
    particleColor: 'rgba(56, 189, 248, 0.5)',
    ambientBonusDesc: '+35% โอกาสและขนาดรางวัล Lucky Event',
    enAmbientBonusDesc: '+35% Lucky Event Trigger Chance & Magnitude',
    relicRequiredCount: 4,
  },
  {
    id: 'magma_mantle',
    name: 'แก่นหินหลอมเหลวแมกมา',
    enName: 'Magmatic Molten Mantle',
    desc: 'ชั้นหินหลอมเหลวใต้แผ่นเปลือกโลก แหล่งพลังงานความร้อนบรรพกาล',
    enDesc: 'Molten basalt currents circulating beneath tectonic plates, radiating primal heat',
    icon: '🌋',
    bgGradient: 'radial-gradient(ellipse at 50% 30%, #29120e 0%, #1c0b08 60%, #0e0504 100%)',
    particleType: 'embers',
    particleColor: 'rgba(239, 68, 68, 0.55)',
    ambientBonusDesc: '+20% โบนัสจากการอัปเกรดราก (Root Upgrades)',
    enAmbientBonusDesc: '+20% Root Species Upgrade Multipliers',
    relicRequiredCount: 6,
  },
  {
    id: 'sunken_ruins',
    name: 'ซากนครใต้พิภพโบราณ',
    enName: 'Sunken Ancient Metropolis',
    desc: 'ร่องรอยอารยธรรมโบราณที่สาบสูญ เต็มไปด้วยอักขระเวทมนตร์',
    enDesc: 'Drowned monuments of an arcane civilization carved with glowing petroglyphs',
    icon: '🏛️',
    bgGradient: 'radial-gradient(ellipse at 50% 30%, #201328 0%, #150c1b 60%, #09040d 100%)',
    particleType: 'runes',
    particleColor: 'rgba(232, 121, 249, 0.5)',
    ambientBonusDesc: '+20% เมล็ดพันธุ์นิรันดร์เมื่อหว่านใหม่ (Prestige)',
    enAmbientBonusDesc: '+20% Eternal Seeds upon Re-sow (Prestige)',
    relicRequiredCount: 8,
  },
  {
    id: 'gaia_sanctum',
    name: 'วิหารแห่งไกอา',
    enName: 'Sanctum of Gaia',
    desc: 'แก่นกลางของดวงดาว สถานที่สถิตของพลังงานชีวิตนิรันดร์',
    enDesc: 'The planetary core where primordial life essences flow in eternal equilibrium',
    icon: '🌌',
    bgGradient: 'radial-gradient(ellipse at 50% 30%, #2b2410 0%, #1c1709 60%, #0c0a03 100%)',
    particleType: 'stardust',
    particleColor: 'rgba(250, 204, 21, 0.6)',
    ambientBonusDesc: '+30% เรทการผลิตสารอาหารทั้งหมดในฟาร์ม',
    enAmbientBonusDesc: '+30% Global Nutrient Production Rate',
    relicRequiredCount: 10,
  },
];

// Helper functions for Relic & Biome bonuses
