import { RelicDef, RelicRarity } from '@/types/game';

export const RELIC_RARITY_INFO: Record<RelicRarity, { name: string; enName: string; color: string; badgeBg: string; icon: string }> = {
  common: { name: 'ทั่วไป', enName: 'Common', color: '#4ade80', badgeBg: 'rgba(74, 222, 128, 0.15)', icon: '🟢' },
  rare: { name: 'หายาก', enName: 'Rare', color: '#38bdf8', badgeBg: 'rgba(56, 189, 248, 0.15)', icon: '🔵' },
  epic: { name: 'มหากาพย์', enName: 'Epic', color: '#c084fc', badgeBg: 'rgba(192, 132, 252, 0.15)', icon: '🟣' },
  legendary: { name: 'ตำนาน', enName: 'Legendary', color: '#fbbf24', badgeBg: 'rgba(251, 191, 36, 0.15)', icon: '🟡' },
  mythic: { name: 'สิ่งศักดิ์สิทธิ์', enName: 'Mythic', color: '#f43f5e', badgeBg: 'rgba(244, 63, 94, 0.2)', icon: '👑' },
};

export const RELIC_MAX_PIECES: Record<RelicRarity, number> = {
  common: 1,
  rare: 1,
  epic: 1,
  legendary: 1,
  mythic: 1,
};

export const RELIC_DEFS: RelicDef[] = [
  // 🟢 COMMON (Weight: 50, Max: 1)
  {
    id: 'amber',
    name: 'อำพันดึกดำบรรพ์',
    enName: 'Primeval Amber',
    icon: '琥',
    desc: 'ยางไม้โบราณที่ผนึกหยดน้ำค้างล้านปี เสริมพลังการเติบโตของเซลล์รากทุกชนิดทั่วทั้งผืนดิน',
    enDesc: 'Ancient resin sealing primordial dewdrops, permanently vitalizing all subterranean root cells.',
    rarity: 'common',
    dropWeight: 50,
    effectDesc: 'เรทการผลิตรากทุกชนิด +50% (×1.50) ถาวร',
    enEffectDesc: '+50% (×1.50) production rate for all roots permanently',
    baseCost: 50_000_000_000,
    color: '#4ade80',
    maxPieces: 1,
  },
  {
    id: 'aquifer',
    name: 'ไข่มุกตาน้ำบาดาลลึก',
    enName: 'Abyssal Aquifer Pearl',
    icon: '🌊',
    desc: 'หยดน้ำบริสุทธิ์กลั่นตัวจากความดันล้านบรรยากาศใต้โลก หล่อเลี้ยงรากชั้นลึกให้ดูดซับสารอาหารได้ทวีคูณ',
    enDesc: 'Pure condensed droplet forged under extreme pressure, supercharging deep stratum roots.',
    rarity: 'common',
    dropWeight: 50,
    effectDesc: 'รากชั้นลึก (Tier 5 เถารากยักษ์ เป็นต้นไป) เรทผลิต ×3.0 เท่า',
    enEffectDesc: 'Deep roots (Tier 5 Giant Vine and beyond) yield ×3.0 rate',
    baseCost: 200_000_000_000,
    color: '#2dd4bf',
    maxPieces: 1,
  },

  // 🔵 RARE (Weight: 20, Max: 1)
  {
    id: 'geode',
    name: 'จีโอดคริสตัลโบราณ',
    enName: 'Ancient Crystal Geode',
    icon: '💎',
    desc: 'โพรงหินผลึกเรืองแสงที่สะท้อนแสงออโรร่าใต้พิภพ เร่งความถี่และดึงดูดสารอาหารบริสุทธิ์จากปรากฏการณ์ลึกลับ',
    enDesc: 'Luminescent crystal cavity accelerating event frequency and tripling rewards from anomaly orbs.',
    rarity: 'rare',
    dropWeight: 20,
    effectDesc: 'คูลดาวน์อีเวนต์ -35% & สารอาหารจากลูกแก้วเหตุการณ์ ×3.0 เท่า',
    enEffectDesc: 'Event orb cooldown -35% & event nutrients ×3.0',
    baseCost: 5_000_000_000_000,
    color: '#38bdf8',
    maxPieces: 1,
  },
  {
    id: 'chronolith',
    name: 'ศิลาบันทึกกาลเวลา',
    enName: 'Chronolith of Aeons',
    icon: '⏳',
    desc: 'ฟอสซิลหินที่จดจำการไหลผ่านของกาลเวลาใต้แผ่นเปลือกโลก ช่วยสะสมสารอาหารออฟไลน์และเร่งเวลาเมื่อกลับสู่สวน',
    enDesc: 'Fossilized strata capturing timeless subterranean currents, granting extra offline cap and Time Warp on return.',
    rarity: 'rare',
    dropWeight: 20,
    effectDesc: 'เพดานออฟไลน์ +12 ชม. & เมื่อกลับเข้าเกมรับบัฟกาลเวลา (Time Warp) ×2.0 นาน 15 นาที',
    enEffectDesc: '+12h offline cap & 15-minute ×2.0 Time Warp buff upon return',
    baseCost: 50_000_000_000_000,
    color: '#60a5fa',
    maxPieces: 1,
  },
  {
    id: 'magmastone',
    name: 'ศิลาแก่นเพลิงพิภพ',
    enName: 'Magmatic Corestone',
    icon: '🌋',
    desc: 'ผลึกหินหลอมเหลวที่ซึมซับพลังงานจากการเวียนว่ายตายเกิด ทุกครั้งที่หว่านใหม่และตื่นรู้จะทวีพลัง 3 เสาหลักอย่างถาวร',
    enDesc: 'Geothermal stone absorbing the cyclical energy of rebirth, stacking permanent bonuses from Prestige & Transcendence.',
    rarity: 'rare',
    dropWeight: 20,
    effectDesc: 'พลังแห่งการเวียนว่าย: Prestige (+1%) / ตื่นรู้ (+3%) มอบ Stack บูสต์ Synergy, Echoes, และเมล็ดนิรันดร์ (สูงสุด +100%)',
    enEffectDesc: 'Cycle Resonance: Prestige (+1%) / Transcendence (+3%) grants stack boosting Synergy, Echoes, & Seeds (Max +100%)',
    baseCost: 500_000_000_000_000,
    color: '#f97316',
    maxPieces: 1,
  },

  // 🟣 EPIC (Weight: 8, Max: 1)
  {
    id: 'mycocore',
    name: 'ฟอสซิลไมคอร์ไรซาบรรพกาล',
    enName: 'Primordial Mycocore',
    icon: '🍄',
    desc: 'แก่นสปอร์บรรพบุรุษเชื้อราที่สร้างเครือข่ายเชื่อมโยงรากไม้ทั้งผืนโลก เปลี่ยนรากต้นเกมเป็นแบตเตอรี่ส่งพลังอันมหาศาล',
    enDesc: 'Ancestral fungal network turning early roots into colossal synergy multipliers for top-tier root engines.',
    rarity: 'epic',
    dropWeight: 8,
    effectDesc: 'เครือข่ายราก (Synergies) ให้ผลผลิตเพิ่มเป็น +0.25%/ต้น (แรงขึ้น 3 เท่า!) และปลดล็อคเครือข่ายได้ตั้งแต่ 25 ต้น',
    enEffectDesc: 'Root Synergies yield +0.25%/unit (×3 power!) and unlocks earlier at 25 owned roots',
    baseCost: 15_000_000_000_000_000,
    color: '#c084fc',
    maxPieces: 1,
  },
  {
    id: 'crown',
    name: 'มงกุฎพฤกษาปฐมกาล',
    enName: 'Crown of the First Tree',
    icon: '🏵️',
    desc: 'กิ่งก้านที่กลายเป็นหินของต้นไม้ต้นแรกของโลก เปล่งพลังสะท้อนอันไร้ขอบเขตสู่รากไม้ทุกสายพันธุ์',
    enDesc: 'Petrified crown boughs of the genesis tree, radiating powerful harmonic echo resonance across the whole garden.',
    rarity: 'epic',
    dropWeight: 8,
    effectDesc: 'ตัวคูณสะท้อนราก (Echoes) เพิ่มขึ้น +1.5% ต่อระดับ Echo',
    enEffectDesc: 'Root Echoes grant +1.5% multiplier per echo level',
    baseCost: 150_000_000_000_000_000,
    color: '#a855f7',
    maxPieces: 1,
  },
  {
    id: 'meteorite',
    name: 'อุกกาบาตฝังใต้พิภพ',
    enName: 'Subterranean Meteorite',
    icon: '🪐',
    desc: 'สะเก็ดดาวจากนอกระบบสุริยะที่อุดมด้วยแร่ธาตุต่างมิติ กระตุ้นวิญญาณแห่งโลกให้มอบละอองชีวิตมากขึ้นเมื่อตื่นรู้',
    enDesc: 'Extraterrestrial meteorite core infusing roots with rare cosmic minerals, increasing Gaia Essences gained.',
    rarity: 'epic',
    dropWeight: 8,
    effectDesc: 'ได้รับจิตวิญญาณแห่งไกอา (Gaia Essences) เพิ่มขึ้น +50% เมื่อตื่นรู้',
    enEffectDesc: '+50% Gaia Essences earned upon Transcendence',
    baseCost: 5_000_000_000_000_000_000,
    color: '#e879f9',
    maxPieces: 1,
  },

  // 🟡 LEGENDARY (Weight: 2, Max: 1)
  {
    id: 'ruintablet',
    name: 'แผ่นจารึกอารยธรรมใต้ดิน',
    enName: 'Ancient Ruin Tablet',
    icon: '🏛️',
    desc: 'ศิลาจารึกอักขระโบราณ บันทึกศาสตร์การเพาะปลูกและแตกหน่อของพฤกษาบรรพกาล เพิ่มโอกาสงอกรากฟรีเมื่อทำการเพาะปลูก',
    enDesc: 'Ancient inscribed tablet revealing esoteric agricultural wisdom and spontaneous twin sprouting.',
    rarity: 'legendary',
    dropWeight: 2,
    effectDesc: 'เมื่อซื้อราก มีโอกาส 35% แตกหน่อแถมรากฟรี (+15% ลุ้นแตกหน่อคู่)',
    enEffectDesc: 'Purchasing roots has 35% chance for +1 free sprout (+15% twin sprout)',
    baseCost: 100_000_000_000_000_000_000,
    color: '#fbbf24',
    maxPieces: 1,
  },

  // 👑 MYTHIC (Weight: 0.5, Max: 1)
  {
    id: 'gaiacore',
    name: 'หัวใจแห่งไกอา',
    enName: 'Heart of Gaia',
    icon: '👑',
    desc: 'แก่นกลางของจิตวิญญาณแห่งโลก เมื่อค้นพบจะปลุกพลังโบราณวัตถุทุกชิ้นให้ทวีคูณเป็น 2 เท่าถาวร!',
    enDesc: 'Core spirit of the living Earth. Awakens and permanently doubles (×2) all relic master powers!',
    rarity: 'mythic',
    dropWeight: 0.5,
    effectDesc: '⭐ บูสต์พลังของโบราณวัตถุทุกชิ้นขึ้นเป็น 2 เท่า (×2) ถาวร!',
    enEffectDesc: '⭐ Permanently doubles (×2) the effects of all relics!',
    baseCost: 10_000_000_000_000_000_000_000,
    color: '#f43f5e',
    maxPieces: 1,
  },
];

export const TOTAL_RELICS = RELIC_DEFS.length;
