import { AchievementCategoryInfo, AchievementDef } from '@/types/achievements';
import { MODULE_DEFS } from './gameData';

export const ACHIEVEMENT_CATEGORIES: AchievementCategoryInfo[] = [
  { id: 'roots', name: 'การแผ่ขยายราก', icon: '🌿' },
  { id: 'economy', name: 'เศรษฐกิจ & ผลผลิต', icon: '⚡' },
  { id: 'prestige', name: 'การหว่านใหม่', icon: '🌌' },
  { id: 'luck', name: 'โชคชะตา & อีเวนต์', icon: '🍀' },
  { id: 'skins', name: 'สกิน & แฟชั่น', icon: '🎨' },
  { id: 'time', name: 'เวลา & ความผูกพัน', icon: '⏳' },
];

export const ACHIEVEMENTS: AchievementDef[] = [
  // ===== 🌿 หมวด 1: การเติบโต & การแผ่ขยายราก (Root Progression) =====
  {
    id: 'root_1',
    category: 'roots',
    title: 'ก้าวแรกสู่ดิน',
    desc: 'ซื้อรากเสริมรวม 1 ต้น',
    icon: '🌱',
    check: (s) => s.totalOwned >= 1,
  },
  {
    id: 'root_50',
    category: 'roots',
    title: 'รากแตกแขนง',
    desc: 'มีรากเสริมรวมสะสม 50 ต้น',
    icon: '🌿',
    check: (s) => s.totalOwned >= 50,
  },
  {
    id: 'root_250',
    category: 'roots',
    title: 'รากไม้พันปี',
    desc: 'มีรากเสริมรวมสะสม 250 ต้น',
    icon: '🌲',
    check: (s) => s.totalOwned >= 250,
  },
  {
    id: 'root_1000',
    category: 'roots',
    title: 'พฤกษานิรันดร์',
    desc: 'มีรากเสริมรวมสะสม 1,000 ต้น',
    icon: '🌳',
    check: (s) => s.totalOwned >= 1000,
  },
  {
    id: 'root_2500',
    category: 'roots',
    title: 'อาณาจักรราก',
    desc: 'มีรากเสริมรวมสะสม 2,500 ต้น',
    icon: '🌴',
    check: (s) => s.totalOwned >= 2500,
  },
  {
    id: 'all_modules_unlocked',
    category: 'roots',
    title: 'นักสะสมสายพันธุ์',
    desc: 'ปลดล็อกรากเสริมครบทุกชนิดในร้านค้า',
    icon: '📜',
    check: (s) => MODULE_DEFS.every(d => (s.owned[d.id] || 0) >= 1),
  },
  {
    id: 'apex_root_10',
    category: 'roots',
    title: 'รากเอกอุ',
    desc: 'มีรากเสริมระดับสูงสุดอย่างน้อย 10 ต้น',
    icon: '👑',
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 10;
    },
  },
  {
    id: 'upgrade_1',
    category: 'roots',
    title: 'อัพเกรดรากขั้นแรก',
    desc: 'อัพเกรดรากเสริมชนิดใดก็ได้แตะเลเวล 1',
    icon: '⬆️',
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 1),
  },
  {
    id: 'upgrade_5',
    category: 'roots',
    title: 'ก้าวกระโดด ×2',
    desc: 'อัพเกรดรากเสริมแตะเลเวล 5 (รับโบนัส ×2 Milestone)',
    icon: '⭐',
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 5),
  },
  {
    id: 'echo_1',
    category: 'roots',
    title: 'สะท้อนรากแรก',
    desc: 'ซื้อสะท้อนราก (Echo) ครั้งแรก',
    icon: '✨',
    check: (s) => Object.values(s.echoes || {}).some(lv => lv >= 1),
  },
  {
    id: 'echo_10',
    category: 'roots',
    title: 'สะท้อนประสานเสียง',
    desc: 'ซื้อสะท้อนรากสะสมรวม 10 ครั้ง',
    icon: '🔔',
    check: (s) => Object.values(s.echoes || {}).reduce((a, b) => a + b, 0) >= 10,
  },

  // ===== ⚡ หมวด 2: เศรษฐกิจ & ผลผลิตสารอาหาร (Economy & Rate) =====
  {
    id: 'nutrients_1k',
    category: 'economy',
    title: 'หยดน้ำสร้างป่า',
    desc: 'สะสมสารอาหารครบ 1,000 (1K)',
    icon: '💧',
    check: (s) => s.nutrients >= 1000 || s.runEarned >= 1000,
  },
  {
    id: 'nutrients_1m',
    category: 'economy',
    title: 'มหาเศรษฐีผืนดิน',
    desc: 'สะสมสารอาหารครบ 1,000,000 (1M)',
    icon: '💰',
    check: (s) => s.nutrients >= 1e6 || s.runEarned >= 1e6,
  },
  {
    id: 'nutrients_1b',
    category: 'economy',
    title: 'ขุมทรัพย์ใต้พิภพ',
    desc: 'สะสมสารอาหารครบ 1,000,000,000 (1B)',
    icon: '💎',
    check: (s) => s.nutrients >= 1e9 || s.runEarned >= 1e9,
  },
  {
    id: 'nutrients_1t',
    category: 'economy',
    title: 'ความอุดมสมบูรณ์ไร้ขีดจำกัด',
    desc: 'สะสมสารอาหารครบ 1T (Trillion)',
    icon: '🌟',
    check: (s) => s.nutrients >= 1e12 || s.runEarned >= 1e12,
  },
  {
    id: 'nutrients_1qa',
    category: 'economy',
    title: 'พลังแห่งจักรวาล',
    desc: 'สะสมสารอาหารครบ 1Qa (Quadrillion)',
    icon: '🌌',
    check: (s) => s.nutrients >= 1e15 || s.runEarned >= 1e15,
  },
  {
    id: 'rate_10k',
    category: 'economy',
    title: 'เร่งฝีเท้า',
    desc: 'ผลิตสารอาหารเกิน 10,000 / วินาที',
    icon: '⚡',
    check: (_, rate) => rate >= 10000,
  },
  {
    id: 'rate_10m',
    category: 'economy',
    title: 'น้ำตกสารอาหาร',
    desc: 'ผลิตสารอาหารเกิน 10,000,000 / วินาที',
    icon: '🌊',
    check: (_, rate) => rate >= 1e7,
  },
  {
    id: 'rate_100b',
    category: 'economy',
    title: 'พลังไหลบ่า',
    desc: 'ผลิตสารอาหารเกิน 100,000,000,000 / วินาที (100B/วิ)',
    icon: '🔥',
    check: (_, rate) => rate >= 1e11,
  },

  // ===== 🌌 หมวด 3: การหว่านใหม่ & ความเป็นนิรันดร์ (Prestige & Eternity) =====
  {
    id: 'prestige_1',
    category: 'prestige',
    title: 'วัฏจักรใหม่',
    desc: 'ทำการ Prestige (หว่านใหม่) ครั้งแรก',
    icon: '🔄',
    check: (s) => (s.stats?.prestigeCount || 0) >= 1 || s.eternalSeeds > 0,
  },
  {
    id: 'prestige_5',
    category: 'prestige',
    title: 'การเดินทางที่ไม่สิ้นสุด',
    desc: 'Prestige หว่านใหม่สะสมครบ 5 ครั้ง',
    icon: '🔁',
    check: (s) => (s.stats?.prestigeCount || 0) >= 5,
  },
  {
    id: 'prestige_20',
    category: 'prestige',
    title: 'ผู้ตรัสรู้ใต้ดิน',
    desc: 'Prestige หว่านใหม่สะสมครบ 20 ครั้ง',
    icon: '🧘',
    check: (s) => (s.stats?.prestigeCount || 0) >= 20,
  },
  {
    id: 'seeds_10',
    category: 'prestige',
    title: 'เก็บเกี่ยวเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 10 เมล็ด',
    icon: '🌱',
    check: (s) => s.eternalSeeds >= 10 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 10,
  },
  {
    id: 'seeds_1k',
    category: 'prestige',
    title: 'คลังเมล็ดดวงดาว',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000 เมล็ด',
    icon: '✨',
    check: (s) => s.eternalSeeds >= 1000 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1000,
  },
  {
    id: 'seeds_100k',
    category: 'prestige',
    title: 'มหาเศรษฐีเมล็ดนิรันดร์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 100,000 เมล็ด',
    icon: '🌌',
    check: (s) => s.eternalSeeds >= 100000 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 100000,
  },
  {
    id: 'full_auto_unlocked',
    category: 'prestige',
    title: 'สายออโต้เต็มรูปแบบ',
    desc: 'ปลดล็อก ออโต้ราก + ออโต้อีเวนต์ + ออโต้หว่านใหม่ ครบทั้ง 3 สาย',
    icon: '🤖',
    check: (s) => s.prestige.autoRoot && s.prestige.autoEvent && s.prestige.autoReset,
  },

  // ===== 🍀 หมวด 4: โชคชะตา & เหตุการณ์พิเศษ (Luck & Events) =====
  {
    id: 'event_1',
    category: 'luck',
    title: 'ตาไวคว้าทัน',
    desc: 'คลิกเก็บอีเวนต์บนจอครั้งแรก',
    icon: '🎯',
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 1,
  },
  {
    id: 'event_25',
    category: 'luck',
    title: 'นักล่าสมบัติ',
    desc: 'เก็บอีเวนต์สะสมครบ 25 ครั้ง',
    icon: '🎁',
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 25,
  },
  {
    id: 'event_100',
    category: 'luck',
    title: 'ผู้ไม่เคยพลาด',
    desc: 'เก็บอีเวนต์สะสมครบ 100 ครั้ง',
    icon: '⚡',
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 100,
  },
  {
    id: 'lucky_1',
    category: 'luck',
    title: 'แจ็กพอตแห่งโชคชะตา',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) ครั้งแรก',
    icon: '🍀',
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 1,
  },
  {
    id: 'super_jackpot',
    category: 'luck',
    title: 'แจ็กพอตซ้อนแจ็กพอต',
    desc: 'เก็บกล่อง 🎁 ได้รับสารอาหารก้อนโตขณะมีบัฟโชคดีทำงานอยู่',
    icon: '💥',
    check: (s) => s.stats?.superJackpotClaimed === true,
  },

  // ===== 🎨 หมวด 5: สกิน & สไตล์ (Aesthetics & Customization) =====
  {
    id: 'skin_equip_custom',
    category: 'skins',
    title: 'นักแต่งสวน',
    desc: 'สวมใส่สกินพิเศษรูปแบบใดก็ได้',
    icon: '🎨',
    check: (s) => s.prestige.activeSkin !== 'none',
  },
  {
    id: 'skins_all_unlocked',
    category: 'skins',
    title: 'ตู้เสื้อผ้ารากไม้',
    desc: 'ปลดล็อกสกินในร้าน Prestige ครบทั้ง 4 รูปแบบ',
    icon: '👗',
    check: (s) =>
      s.prestige.auraRoots &&
      s.prestige.skinSameOrigin &&
      s.prestige.skinGrayscale &&
      s.prestige.skinGradient,
  },

  // ===== ⏳ หมวด 6: เวลา & ความผูกพัน (Dedication & Time) =====
  {
    id: 'playtime_10m',
    category: 'time',
    title: 'รดน้ำอย่างใจเย็น',
    desc: 'เวลาเล่นสะสมรวมครบ 10 นาที',
    icon: '⏱️',
    check: (s) => s.totalPlayTimeSeconds >= 600,
  },
  {
    id: 'playtime_1h',
    category: 'time',
    title: 'ผู้เฝ้ามองราก',
    desc: 'เวลาเล่นสะสมรวมครบ 1 ชั่วโมง',
    icon: '⏳',
    check: (s) => s.totalPlayTimeSeconds >= 3600,
  },
  {
    id: 'playtime_12h',
    category: 'time',
    title: 'ป่าไม้ตลอดกาล',
    desc: 'เวลาเล่นสะสมรวมครบ 12 ชั่วโมง',
    icon: '🏆',
    check: (s) => s.totalPlayTimeSeconds >= 43200,
  },
  {
    id: 'offline_1h',
    category: 'time',
    title: 'กลับมาดูแล',
    desc: 'เก็บผลผลิตออฟไลน์ (Offline Gain) ที่หายไปเกิน 1 ชั่วโมง',
    icon: '🏡',
    check: (s) => (s.stats?.maxOfflineTimeSeconds || 0) >= 3600,
  },
];
