import { AchievementCategoryInfo, AchievementDef } from '@/types/achievements';
import { MODULE_DEFS } from './modules';
import { hasRelic, relicsCount, relicCycleResonanceStack } from './relics';
import { SKIN_DEFS, isSkinUnlocked, UI_THEME_DEFS, isUIThemeUnlocked } from './cosmetics';

export const ACHIEVEMENT_CATEGORIES: AchievementCategoryInfo[] = [
  { id: 'roots', name: 'การแผ่ขยายราก', icon: '🌿' },
  { id: 'economy', name: 'เศรษฐกิจ & ผลผลิต', icon: '⚡' },
  { id: 'prestige', name: 'การหว่านใหม่', icon: '🌌' },
  { id: 'luck', name: 'โชคชะตา & อีเวนต์', icon: '🍀' },
  { id: 'relics', name: 'โบราณวัตถุ & ชีวนิเวศ', icon: '🏺' },
  { id: 'gaia', name: 'การตื่นรู้ & การทดลอง', icon: '🌍' },
  { id: 'skins', name: 'สกิน & แฟชั่น', icon: '🎨' },
  { id: 'time', name: 'เวลา & ความผูกพัน', icon: '⏳' },
];

export const ACHIEVEMENTS: AchievementDef[] = [
  // ===== 🌿 หมวด 1: การเติบโต & การแผ่ขยายราก (Root Progression) =====
  {
    id: 'root_1',
    category: 'roots',
    title: 'ก้าวแรกสู่ดิน',
    desc: 'ซื้อรากเสริมรวม 1 ต้น',
    icon: '🌱',
    bonusPct: 1,
    check: (s) => s.totalOwned >= 1,
  },
  {
    id: 'root_50',
    category: 'roots',
    title: 'รากแตกแขนง',
    desc: 'มีรากเสริมรวมสะสม 50 ต้น',
    icon: '🌿',
    bonusPct: 2,
    check: (s) => s.totalOwned >= 50,
  },
  {
    id: 'root_250',
    category: 'roots',
    title: 'รากไม้พันปี',
    desc: 'มีรากเสริมรวมสะสม 250 ต้น',
    icon: '🌲',
    bonusPct: 3,
    check: (s) => s.totalOwned >= 250,
  },
  {
    id: 'root_1000',
    category: 'roots',
    title: 'พฤกษานิรันดร์',
    desc: 'มีรากเสริมรวมสะสม 1,000 ต้น',
    icon: '🌳',
    bonusPct: 5,
    check: (s) => s.totalOwned >= 1000,
  },
  {
    id: 'root_2500',
    category: 'roots',
    title: 'อาณาจักรราก',
    desc: 'มีรากเสริมรวมสะสม 2,500 ต้น',
    icon: '🌴',
    bonusPct: 6,
    check: (s) => s.totalOwned >= 2500,
  },
  {
    id: 'root_5000',
    category: 'roots',
    title: 'เครือข่ายรากไร้ขอบเขต',
    desc: 'มีรากเสริมรวมสะสม 5,000 ต้น',
    icon: '🎋',
    bonusPct: 7,
    check: (s) => s.totalOwned >= 5000,
  },
  {
    id: 'root_10000',
    category: 'roots',
    title: 'ผืนป่าครอบพิภพ',
    desc: 'มีรากเสริมรวมสะสม 10,000 ต้น',
    icon: '🪐',
    bonusPct: 8,
    check: (s) => s.totalOwned >= 10000,
  },
  {
    id: 'root_25000',
    category: 'roots',
    title: 'ผืนพิภพแห่งรากไม้',
    desc: 'มีรากเสริมรวมสะสม 25,000 ต้น',
    icon: '🌍',
    bonusPct: 9,
    check: (s) => s.totalOwned >= 25000,
  },
  {
    id: 'root_50000',
    category: 'roots',
    title: 'รากไม้โอบล้อมจักรวาล',
    desc: 'มีรากเสริมรวมสะสม 50,000 ต้น',
    icon: '🌌',
    bonusPct: 10,
    check: (s) => s.totalOwned >= 50000,
  },
  {
    id: 'fine_root_100',
    category: 'roots',
    title: 'ทุ่งรากฝอย',
    desc: 'มีรากฝอย (Fine Roots) สะสม 100 ต้น',
    icon: '🌾',
    bonusPct: 2,
    check: (s) => (s.owned['fine'] || 0) >= 100,
  },
  {
    id: 'fine_root_500',
    category: 'roots',
    title: 'พรมรากฝอยใต้ดิน',
    desc: 'มีรากฝอย (Fine Roots) สะสม 500 ต้น',
    icon: '🌱',
    bonusPct: 5,
    check: (s) => (s.owned['fine'] || 0) >= 500,
  },
  {
    id: 'fine_root_1000',
    category: 'roots',
    title: 'มหาสมุทรรากฝอย',
    desc: 'มีรากฝอย (Fine Roots) สะสม 1,000 ต้น',
    icon: '🌿',
    bonusPct: 10,
    check: (s) => (s.owned['fine'] || 0) >= 1000,
  },
  {
    id: 'all_modules_unlocked',
    category: 'roots',
    title: 'นักสะสมสายพันธุ์',
    desc: 'ปลดล็อกรากเสริมครบทุกชนิดในร้านค้า (21 สายพันธุ์)',
    icon: '📜',
    bonusPct: 10,
    check: (s) => MODULE_DEFS.every(d => (s.owned[d.id] || 0) >= 1),
  },
  {
    id: 'apex_root_1',
    category: 'roots',
    title: 'กำเนิดรากต้นไม้โลก',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) รากขั้นสูงสุดอย่างน้อย 1 ต้น',
    icon: '👑',
    bonusPct: 5,
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 1;
    },
  },
  {
    id: 'apex_root_10',
    category: 'roots',
    title: 'เสาค้ำจุนใต้พิภพ',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) อย่างน้อย 10 ต้น',
    icon: '💎',
    bonusPct: 8,
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 10;
    },
  },
  {
    id: 'apex_root_50',
    category: 'roots',
    title: 'จักรพรรดิแห่งพฤกษาอนันต์',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) อย่างน้อย 50 ต้น',
    icon: '🏛️',
    bonusPct: 10,
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 50;
    },
  },
  {
    id: 'apex_root_100',
    category: 'roots',
    title: 'อิกดราซิลค้ำจุนทุกมิติ',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) อย่างน้อย 100 ต้น',
    icon: '🌳',
    bonusPct: 15,
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 100;
    },
  },
  {
    id: 'upgrade_1',
    category: 'roots',
    title: 'อัพเกรดรากขั้นแรก',
    desc: 'อัพเกรดรากเสริมชนิดใดก็ได้แตะเลเวล 1',
    icon: '⬆️',
    bonusPct: 1,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 1),
  },
  {
    id: 'upgrade_5',
    category: 'roots',
    title: 'ก้าวกระโดด ×2',
    desc: 'อัพเกรดรากเสริมแตะเลเวล 5 (รับโบนัส ×2 Milestone)',
    icon: '⭐',
    bonusPct: 3,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 5),
  },
  {
    id: 'upgrade_10',
    category: 'roots',
    title: 'พลังแห่งวิวัฒนาการ',
    desc: 'อัพเกรดรากเสริมชนิดใดก็ได้แตะเลเวล 10',
    icon: '🌟',
    bonusPct: 7,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 10),
  },
  {
    id: 'echo_1',
    category: 'roots',
    title: 'สะท้อนรากแรก',
    desc: 'ซื้อสะท้อนราก (Echo) ครั้งแรก',
    icon: '✨',
    bonusPct: 2,
    check: (s) => Object.values(s.echoes || {}).some(lv => lv >= 1),
  },
  {
    id: 'echo_10',
    category: 'roots',
    title: 'สะท้อนประสานเสียง',
    desc: 'ซื้อสะท้อนรากสะสมรวม 10 ครั้ง',
    icon: '🔔',
    bonusPct: 5,
    check: (s) => Object.values(s.echoes || {}).reduce((a, b) => a + b, 0) >= 10,
  },
  {
    id: 'echo_all',
    category: 'roots',
    title: 'เสียงก้องกังวานทั้งผืนดิน',
    desc: 'ปลดล็อกสะท้อนราก (Echo) ครบทั้ง 21 สายพันธุ์',
    icon: '🎶',
    bonusPct: 10,
    check: (s) => MODULE_DEFS.every(d => (s.echoes?.[d.id] || 0) >= 1),
  },
  {
    id: 'synergy_1',
    category: 'roots',
    title: 'สายสัมพันธ์แรก',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) ชนิดใดก็ได้ 1 ชนิด',
    icon: '🌐',
    bonusPct: 3,
    check: (s) => Object.values(s.rootSynergies || {}).some(v => !!v),
  },
  {
    id: 'synergy_10',
    category: 'roots',
    title: 'โครงข่ายรากพิภพ',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) สะสมครบ 10 ชนิด',
    icon: '🕸️',
    bonusPct: 6,
    check: (s) => Object.values(s.rootSynergies || {}).filter(v => !!v).length >= 10,
  },
  {
    id: 'synergy_all',
    category: 'roots',
    title: 'เอกภาพแห่งผืนดิน',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) ครบทั้ง 21 สายพันธุ์',
    icon: '🌍',
    bonusPct: 10,
    check: (s) => MODULE_DEFS.every(d => !!s.rootSynergies?.[d.id]),
  },

  // ===== ⚡ หมวด 2: เศรษฐกิจ & ผลผลิตสารอาหาร (Economy & Rate) =====
  {
    id: 'nutrients_1k',
    category: 'economy',
    title: 'หยดน้ำสร้างป่า',
    desc: 'สะสมสารอาหารครบ 1,000 (1K)',
    icon: '💧',
    bonusPct: 1,
    check: (s) => s.nutrients >= 1000 || s.runEarned >= 1000 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1000,
  },
  {
    id: 'nutrients_1m',
    category: 'economy',
    title: 'มหาเศรษฐีผืนดิน',
    desc: 'สะสมสารอาหารครบ 1,000,000 (1M)',
    icon: '💰',
    bonusPct: 2,
    check: (s) => s.nutrients >= 1e6 || s.runEarned >= 1e6 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e6,
  },
  {
    id: 'nutrients_1b',
    category: 'economy',
    title: 'ขุมทรัพย์ใต้พิภพ',
    desc: 'สะสมสารอาหารครบ 1,000,000,000 (1B)',
    icon: '💎',
    bonusPct: 3,
    check: (s) => s.nutrients >= 1e9 || s.runEarned >= 1e9 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e9,
  },
  {
    id: 'nutrients_100b',
    category: 'economy',
    title: 'ขุมพลังมหาศาล',
    desc: 'สะสมสารอาหารครบ 100,000,000,000 (100B)',
    icon: '🔮',
    bonusPct: 4,
    check: (s) => s.nutrients >= 1e11 || s.runEarned >= 1e11 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e11,
  },
  {
    id: 'nutrients_1t',
    category: 'economy',
    title: 'ความอุดมสมบูรณ์ไร้ขีดจำกัด',
    desc: 'สะสมสารอาหารครบ 1T (Trillion)',
    icon: '🌟',
    bonusPct: 5,
    check: (s) => s.nutrients >= 1e12 || s.runEarned >= 1e12 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e12,
  },
  {
    id: 'nutrients_100t',
    category: 'economy',
    title: 'ทะเลสาบสารอาหาร',
    desc: 'สะสมสารอาหารครบ 100T (100 Trillion)',
    icon: '🌊',
    bonusPct: 6,
    check: (s) => s.nutrients >= 1e14 || s.runEarned >= 1e14 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e14,
  },
  {
    id: 'nutrients_1qa',
    category: 'economy',
    title: 'พลังแห่งจักรวาล',
    desc: 'สะสมสารอาหารครบ 1Qa (Quadrillion)',
    icon: '🌌',
    bonusPct: 7,
    check: (s) => s.nutrients >= 1e15 || s.runEarned >= 1e15 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e15,
  },
  {
    id: 'nutrients_100qa',
    category: 'economy',
    title: 'มหาสมุทรแห่งชีวิต',
    desc: 'สะสมสารอาหารครบ 100Qa (100 Quadrillion)',
    icon: '🪐',
    bonusPct: 8,
    check: (s) => s.nutrients >= 1e17 || s.runEarned >= 1e17 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e17,
  },
  {
    id: 'nutrients_1qi',
    category: 'economy',
    title: 'แก่นแท้แห่งสรรพสิ่ง',
    desc: 'สะสมสารอาหารครบ 1Qi (Quintillion)',
    icon: '☀️',
    bonusPct: 9,
    check: (s) => s.nutrients >= 1e18 || s.runEarned >= 1e18 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e18,
  },
  {
    id: 'nutrients_1sx',
    category: 'economy',
    title: 'กำเนิดจักรวาลใหม่',
    desc: 'สะสมสารอาหารครบ 1Sx (Sextillion)',
    icon: '💫',
    bonusPct: 10,
    check: (s) => s.nutrients >= 1e21 || s.runEarned >= 1e21 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e21,
  },
  {
    id: 'nutrients_1sp',
    category: 'economy',
    title: 'มหันตภัยสารอาหาร',
    desc: 'สะสมสารอาหารครบ 1Sp (Septillion)',
    icon: '🪐',
    bonusPct: 10,
    check: (s) => s.nutrients >= 1e24 || s.runEarned >= 1e24 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e24,
  },
  {
    id: 'nutrients_1oc',
    category: 'economy',
    title: 'ขุมพลังไร้ที่สิ้นสุด',
    desc: 'สะสมสารอาหารครบ 1Oc (Octillion)',
    icon: '👑',
    bonusPct: 10,
    check: (s) => s.nutrients >= 1e27 || s.runEarned >= 1e27 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e27,
  },
  {
    id: 'nutrients_1no',
    category: 'economy',
    title: 'มหาพิภพไร้ขอบเขต',
    desc: 'สะสมสารอาหารครบ 1No (Nonillion)',
    icon: '🪐',
    bonusPct: 10,
    check: (s) => s.nutrients >= 1e30 || s.runEarned >= 1e30 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e30,
  },
  {
    id: 'nutrients_1dc',
    category: 'economy',
    title: 'แก่นสารอาหารจักรวาล',
    desc: 'สะสมสารอาหารครบ 1Dc (Decillion)',
    icon: '🔮',
    bonusPct: 12,
    check: (s) => s.nutrients >= 1e33 || s.runEarned >= 1e33 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e33,
  },
  {
    id: 'nutrients_1udc',
    category: 'economy',
    title: 'มหาสมุทรพลังงานอนันต์',
    desc: 'สะสมสารอาหารครบ 1UDc (Undecillion)',
    icon: '🌌',
    bonusPct: 15,
    check: (s) => s.nutrients >= 1e36 || s.runEarned >= 1e36 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e36,
  },
  {
    id: 'nutrients_1qadc',
    category: 'economy',
    title: 'พฤกษากลืนมิติเวลา',
    desc: 'สะสมสารอาหารครบ 1QaDc (Quattuordecillion)',
    icon: '⏳',
    bonusPct: 18,
    check: (s) => s.nutrients >= 1e45 || s.runEarned >= 1e45 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e45,
  },
  {
    id: 'nutrients_1vg',
    category: 'economy',
    title: 'ผู้สร้างจักรวาลปฐมกาล',
    desc: 'สะสมสารอาหารครบ 1Vg (Vigintillion)',
    icon: '👑',
    bonusPct: 20,
    check: (s) => s.nutrients >= 1e63 || s.runEarned >= 1e63 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e63,
  },
  {
    id: 'rate_10k',
    category: 'economy',
    title: 'เร่งฝีเท้า',
    desc: 'ผลิตสารอาหารเกิน 10,000 / วินาที',
    icon: '⚡',
    bonusPct: 1,
    check: (_, rate) => rate >= 10000,
  },
  {
    id: 'rate_10m',
    category: 'economy',
    title: 'น้ำตกสารอาหาร',
    desc: 'ผลิตสารอาหารเกิน 10,000,000 / วินาที',
    icon: '🌊',
    bonusPct: 3,
    check: (_, rate) => rate >= 1e7,
  },
  {
    id: 'rate_100b',
    category: 'economy',
    title: 'พลังไหลบ่า',
    desc: 'ผลิตสารอาหารเกิน 100,000,000,000 / วินาที (100B/วิ)',
    icon: '🔥',
    bonusPct: 5,
    check: (_, rate) => rate >= 1e11,
  },
  {
    id: 'rate_1t',
    category: 'economy',
    title: 'มหาวาตภัยสารอาหาร',
    desc: 'ผลิตสารอาหารเกิน 1,000,000,000,000 / วินาที (1T/วิ)',
    icon: '🌪️',
    bonusPct: 7,
    check: (_, rate) => rate >= 1e12,
  },
  {
    id: 'rate_1qa',
    category: 'economy',
    title: 'ดัชนีการเติบโตระดับดวงดาว',
    desc: 'ผลิตสารอาหารเกิน 1Qa / วินาที (Quadrillion/วิ)',
    icon: '🌠',
    bonusPct: 8,
    check: (_, rate) => rate >= 1e15,
  },
  {
    id: 'rate_1qi',
    category: 'economy',
    title: 'พลังขับเคลื่อนแห่งอนันต์',
    desc: 'ผลิตสารอาหารเกิน 1Qi / วินาที (Quintillion/วิ)',
    icon: '🌌',
    bonusPct: 9,
    check: (_, rate) => rate >= 1e18,
  },
  {
    id: 'rate_1sx',
    category: 'economy',
    title: 'คลื่นพลังเซกทิลเลียน',
    desc: 'ผลิตสารอาหารเกิน 1Sx / วินาที (Sextillion/วิ)',
    icon: '⚡',
    bonusPct: 10,
    check: (_, rate) => rate >= 1e21,
  },
  {
    id: 'rate_1sp',
    category: 'economy',
    title: 'อัตราการเติบโตระดับดาราจักร',
    desc: 'ผลิตสารอาหารเกิน 1Sp / วินาที (Septillion/วิ)',
    icon: '🌌',
    bonusPct: 10,
    check: (_, rate) => rate >= 1e24,
  },
  {
    id: 'rate_1oc',
    category: 'economy',
    title: 'การระเบิดแห่งบิ๊กแบง',
    desc: 'ผลิตสารอาหารเกิน 1Oc / วินาที (Octillion/วิ)',
    icon: '💥',
    bonusPct: 12,
    check: (_, rate) => rate >= 1e27,
  },
  {
    id: 'rate_1no',
    category: 'economy',
    title: 'อัตราเร่งแห่งเอกภพ',
    desc: 'ผลิตสารอาหารเกิน 1No / วินาที (Nonillion/วิ)',
    icon: '🪐',
    bonusPct: 15,
    check: (_, rate) => rate >= 1e30,
  },
  {
    id: 'rate_1dc',
    category: 'economy',
    title: 'มหาพฤกษาเหนือจักรวาล',
    desc: 'ผลิตสารอาหารเกิน 1Dc / วินาที (Decillion/วิ)',
    icon: '🌟',
    bonusPct: 20,
    check: (_, rate) => rate >= 1e33,
  },

  // ===== 🌌 หมวด 3: การหว่านใหม่ & ความเป็นนิรันดร์ (Prestige & Eternity) =====
  {
    id: 'prestige_1',
    category: 'prestige',
    title: 'วัฏจักรใหม่',
    desc: 'ทำการ Prestige (หว่านใหม่) ครั้งแรก',
    icon: '🔄',
    bonusPct: 2,
    check: (s) => (s.stats?.prestigeCount || 0) >= 1 || s.eternalSeeds > 0,
  },
  {
    id: 'prestige_5',
    category: 'prestige',
    title: 'การเดินทางที่ไม่สิ้นสุด',
    desc: 'Prestige หว่านใหม่สะสมครบ 5 ครั้ง',
    icon: '🔁',
    bonusPct: 4,
    check: (s) => (s.stats?.prestigeCount || 0) >= 5,
  },
  {
    id: 'prestige_20',
    category: 'prestige',
    title: 'ผู้ตรัสรู้ใต้ดิน',
    desc: 'Prestige หว่านใหม่สะสมครบ 20 ครั้ง',
    icon: '🧘',
    bonusPct: 7,
    check: (s) => (s.stats?.prestigeCount || 0) >= 20,
  },
  {
    id: 'prestige_50',
    category: 'prestige',
    title: 'วัฏสงสารนิรันดร์',
    desc: 'Prestige หว่านใหม่สะสมครบ 50 ครั้ง',
    icon: '♾️',
    bonusPct: 10,
    check: (s) => (s.stats?.prestigeCount || 0) >= 50,
  },
  {
    id: 'seeds_10',
    category: 'prestige',
    title: 'เก็บเกี่ยวเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 10 เมล็ด',
    icon: '🌱',
    bonusPct: 1,
    check: (s) => s.eternalSeeds >= 10 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 10,
  },
  {
    id: 'seeds_1k',
    category: 'prestige',
    title: 'คลังเมล็ดดวงดาว',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000 เมล็ด',
    icon: '✨',
    bonusPct: 3,
    check: (s) => s.eternalSeeds >= 1000 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1000,
  },
  {
    id: 'seeds_100k',
    category: 'prestige',
    title: 'มหาเศรษฐีเมล็ดนิรันดร์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 100,000 เมล็ด',
    icon: '🌌',
    bonusPct: 5,
    check: (s) => s.eternalSeeds >= 100000 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 100000,
  },
  {
    id: 'seeds_1m',
    category: 'prestige',
    title: 'สวนแห่งเทพนิรันดร์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000,000 เมล็ด (1M)',
    icon: '🪐',
    bonusPct: 8,
    check: (s) => s.eternalSeeds >= 1e6 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e6,
  },
  {
    id: 'seeds_10m',
    category: 'prestige',
    title: 'ดาราจักรเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 10,000,000 เมล็ด (10M)',
    icon: '👑',
    bonusPct: 10,
    check: (s) => s.eternalSeeds >= 1e7 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e7,
  },
  {
    id: 'seeds_50m',
    category: 'prestige',
    title: 'จอมราชันย์แห่งเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 50,000,000 เมล็ด (50M)',
    icon: '💎',
    bonusPct: 10,
    check: (s) => s.eternalSeeds >= 5e7 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 5e7,
  },
  {
    id: 'full_auto_unlocked',
    category: 'prestige',
    title: 'สายออโต้เต็มรูปแบบ',
    desc: 'ปลดล็อก ออโต้สรรพสิ่ง (Universal Automation) ครบจบในตัวเดียว',
    icon: '🤖',
    bonusPct: 8,
    check: (s) => !!s.prestige.autoRoot,
  },
  {
    id: 'golden_seed_max',
    category: 'prestige',
    title: 'เมล็ดทองคำเบ่งบาน',
    desc: 'อัพเกรดเมล็ดพันธุ์ทองคำ (Golden Seeds) แตะเลเวล 5',
    icon: '🏆',
    bonusPct: 7,
    check: (s) => (s.prestige.goldenLevel || 0) >= 5,
  },
  {
    id: 'lucky_duration_max',
    category: 'prestige',
    title: 'โชคชะตายืนยาว',
    desc: 'อัพเกรดระยะเวลาบัฟโชคดีครบ 20 วินาทีเต็ม (สูงสุด)',
    icon: '⏳',
    bonusPct: 10,
    check: (s) => (s.prestige.luckyDurationLevel || 0) >= 15,
  },
  {
    id: 'passive_rate_10',
    category: 'prestige',
    title: 'การดูดซึมไม่หยุดนิ่ง',
    desc: 'อัพเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 10',
    icon: '💧',
    bonusPct: 4,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 10,
  },
  {
    id: 'passive_rate_25',
    category: 'prestige',
    title: 'ชีพจรแห่งผืนดิน',
    desc: 'อัพเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 25',
    icon: '🌊',
    bonusPct: 7,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 25,
  },
  {
    id: 'passive_rate_50',
    category: 'prestige',
    title: 'กระแสรากต่อเนื่อง',
    desc: 'อัพเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 50',
    icon: '🌊',
    bonusPct: 5,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 50,
  },
  {
    id: 'starter_culture_10',
    category: 'prestige',
    title: 'กลิ่นอายหัวเชื้อ',
    desc: 'อัพเกรดหัวเชื้อเริ่มต้น (Starter Culture) แตะเลเวล 10',
    icon: '🌱',
    bonusPct: 3,
    check: (s) => (s.prestige.starterLevel || 0) >= 10,
  },
  {
    id: 'starter_culture_25',
    category: 'prestige',
    title: 'รากฝอยพร้อมสรรพ',
    desc: 'อัพเกรดหัวเชื้อเริ่มต้น (Starter Culture) แตะเลเวล 25',
    icon: '🌿',
    bonusPct: 5,
    check: (s) => (s.prestige.starterLevel || 0) >= 25,
  },
  {
    id: 'golden_seed_25',
    category: 'prestige',
    title: 'ประกายทองคำเบ่งบาน',
    desc: 'อัพเกรดเมล็ดพันธุ์ทองคำ (Golden Seeds) แตะเลเวล 25',
    icon: '🏆',
    bonusPct: 5,
    check: (s) => (s.prestige.goldenLevel || 0) >= 25,
  },

  // ===== 🍀 หมวด 4: โชคชะตา & เหตุการณ์พิเศษ (Luck & Events) =====
  {
    id: 'event_1',
    category: 'luck',
    title: 'ตาไวคว้าทัน',
    desc: 'คลิกเก็บอีเวนต์บนจอครั้งแรก',
    icon: '🎯',
    bonusPct: 1,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 1,
  },
  {
    id: 'event_25',
    category: 'luck',
    title: 'นักล่าสมบัติ',
    desc: 'เก็บอีเวนต์สะสมครบ 25 ครั้ง',
    icon: '🎁',
    bonusPct: 3,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 25,
  },
  {
    id: 'event_100',
    category: 'luck',
    title: 'ผู้ไม่เคยพลาด',
    desc: 'เก็บอีเวนต์สะสมครบ 100 ครั้ง',
    icon: '⚡',
    bonusPct: 6,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 100,
  },
  {
    id: 'event_500',
    category: 'luck',
    title: 'มือเก็บเกี่ยวแห่งตำนาน',
    desc: 'เก็บอีเวนต์สะสมครบ 500 ครั้ง',
    icon: '🌠',
    bonusPct: 10,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 500,
  },
  {
    id: 'lucky_1',
    category: 'luck',
    title: 'แจ็กพอตแห่งโชคชะตา',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) ครั้งแรก',
    icon: '🍀',
    bonusPct: 5,
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 1,
  },
  {
    id: 'lucky_10',
    category: 'luck',
    title: 'เทพแห่งโชคลาภ',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) สะสมครบ 10 ครั้ง',
    icon: '🎲',
    bonusPct: 10,
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 10,
  },
  {
    id: 'super_jackpot',
    category: 'luck',
    title: 'แจ็กพอตซ้อนแจ็กพอต',
    desc: 'เก็บกล่อง 🎁 ได้รับสารอาหารก้อนโตขณะมีบัฟโชคดีทำงานอยู่',
    icon: '💥',
    bonusPct: 10,
    check: (s) => s.stats?.superJackpotClaimed === true,
  },
  {
    id: 'event_bonus_25',
    category: 'luck',
    title: 'ผลตอบแทนงอกเงย',
    desc: 'อัพเกรดโบนัสอีเวนต์ (Event Value Booster) ในร้านหว่านใหม่แตะเลเวล 25',
    icon: '🎁',
    bonusPct: 3,
    check: (s) => (s.prestige.eventBonusLevel || 0) >= 25,
  },
  {
    id: 'event_duration_max',
    category: 'luck',
    title: 'เวลาแห่งบัฟ',
    desc: 'อัพเกรดขยายระยะเวลาบัฟอีเวนต์แตะเลเวล 4 (สูงสุด)',
    icon: '⏳',
    bonusPct: 4,
    check: (s) => (s.prestige.eventDurationLevel || 0) >= 4,
  },
  {
    id: 'lucky_chance_max',
    category: 'luck',
    title: 'ทุ่งโคลเวอร์เบ่งบาน',
    desc: 'อัพเกรดโอกาสพบเจอโชคดีแตะเลเวล 8 (สูงสุด 1.0%)',
    icon: '🍀',
    bonusPct: 5,
    check: (s) => (s.prestige.luckyChanceLevel || 0) >= 8,
  },
  {
    id: 'lucky_magnitude_max',
    category: 'luck',
    title: 'โชคดีสิบเท่าทวีคูณ',
    desc: 'อัพเกรดโชคดีทวีคูณแตะเลเวล 9 (สูงสุด ทบตัวคูณโชคดี ×10)',
    icon: '🎲',
    bonusPct: 5,
    check: (s) => (s.prestige.luckyMagnitudeLevel || 0) >= 9,
  },

  // ===== 🎨 หมวด 5: สกิน & สไตล์ (Aesthetics & Customization) =====
  {
    id: 'skin_equip_custom',
    category: 'skins',
    title: 'นักแต่งสวน',
    desc: 'สวมใส่สกินพิเศษรูปแบบใดก็ได้',
    icon: '🎨',
    bonusPct: 2,
    check: (s) => s.prestige.activeSkin !== 'none',
  },
  {
    id: 'skins_all_unlocked',
    category: 'skins',
    title: 'ตู้เสื้อผ้ารากไม้',
    desc: 'ปลดล็อกสกินรากไม้ในห้องแต่งตัวสะสมครบ 4 รูปแบบ',
    icon: '👗',
    bonusPct: 8,
    check: (s) => SKIN_DEFS.filter(def => def.id !== 'none' && isSkinUnlocked(s, def.id)).length >= 4,
  },
  {
    id: 'theme_equip_custom',
    category: 'skins',
    title: 'จิตรกรแห่งผืนดิน',
    desc: 'สวมใส่ธีมหน้าต่าง UI พิเศษรูปแบบใดก็ได้ที่ไม่ใช่คลาสสิก',
    icon: '🖼️',
    bonusPct: 2,
    check: (s) => !!s.prestige.activeUITheme && s.prestige.activeUITheme !== 'classic',
  },
  {
    id: 'theme_void_sovereign',
    category: 'skins',
    title: 'ราชันย์แห่งมิติสุญญะ',
    desc: 'ปลดล็อกและสวมใส่ธีม UI [🌌 จอมราชันย์แห่งสุญญะ] จากการพิชิตการทดลอง',
    icon: '🌌',
    bonusPct: 5,
    check: (s) => s.prestige.activeUITheme === 'void_sovereign',
  },
  {
    id: 'skins_collector_8',
    category: 'skins',
    title: 'ผู้คลั่งไคล้แฟชั่นรากไม้',
    desc: 'ปลดล็อกสกินรากไม้ในห้องแต่งตัวสะสมครบ 8 รูปแบบ',
    icon: '👘',
    bonusPct: 4,
    check: (s) => SKIN_DEFS.filter(def => def.id !== 'none' && isSkinUnlocked(s, def.id)).length >= 8,
  },
  {
    id: 'skins_collector_12',
    category: 'skins',
    title: 'รันเวย์ใต้พิภพ',
    desc: 'ปลดล็อกสกินรากไม้ในห้องแต่งตัวสะสมครบ 12 รูปแบบ',
    icon: '👑',
    bonusPct: 6,
    check: (s) => SKIN_DEFS.filter(def => def.id !== 'none' && isSkinUnlocked(s, def.id)).length >= 12,
  },
  {
    id: 'skin_nebula_unlocked',
    category: 'skins',
    title: 'รากไม้แห่งดวงดาว',
    desc: 'ครอบครองสกินระดับสูง [🌌 มิติเนบิวลา] หรือ [🪙 มรดกทองคำ]',
    icon: '⭐',
    bonusPct: 5,
    check: (s) => !!s.prestige.skinNebula || !!s.prestige.skinImperial,
  },
  {
    id: 'skin_trial_champions',
    category: 'skins',
    title: 'อาภรณ์แห่งผู้พิชิต',
    desc: 'ปลดล็อกสกินพิเศษจากการพิชิตการทดลองใต้พิภพอย่างน้อย 1 รูปแบบ',
    icon: '⚔️',
    bonusPct: 6,
    check: (s) =>
      isSkinUnlocked(s, 'drought') ||
      isSkinUnlocked(s, 'obsidian') ||
      isSkinUnlocked(s, 'eclipse') ||
      isSkinUnlocked(s, 'permafrost') ||
      isSkinUnlocked(s, 'fulminant'),
  },
  {
    id: 'themes_collector_5',
    category: 'skins',
    title: 'สถาปนิกส่วนหน้า',
    desc: 'ปลดล็อกธีมหน้าต่าง UI ในห้องแต่งตัวสะสมครบ 5 ธีม',
    icon: '🏛️',
    bonusPct: 4,
    check: (s) => UI_THEME_DEFS.filter(t => t.id !== 'classic' && isUIThemeUnlocked(s, t.id)).length >= 5,
  },
  {
    id: 'themes_collector_10',
    category: 'skins',
    title: 'พหุภพแห่งผืนดิน',
    desc: 'ปลดล็อกธีมหน้าต่าง UI ในห้องแต่งตัวสะสมครบ 10 ธีม',
    icon: '🌈',
    bonusPct: 6,
    check: (s) => UI_THEME_DEFS.filter(t => t.id !== 'classic' && isUIThemeUnlocked(s, t.id)).length >= 10,
  },
  {
    id: 'skin_theme_match',
    category: 'skins',
    title: 'คู่สีกลมกลืนแห่งธรรมชาติ',
    desc: 'สวมใส่สกินรากไม้และธีมหน้าต่าง UI ในเซ็ตธีมเดียวกัน (เช่น ซากุระคู่ซากุระ หรือ ไซเบอร์พังก์คู่ไซเบอร์พังก์)',
    icon: '✨',
    bonusPct: 3,
    check: (s) => s.prestige.activeSkin !== 'none' && s.prestige.activeUITheme !== 'classic' && (s.prestige.activeSkin as string) === (s.prestige.activeUITheme as string),
  },
  {
    id: 'wardrobe_grand_master',
    category: 'skins',
    title: 'มหาจักรพรรดิแห่งแฟชั่นรากไม้',
    desc: 'ครอบครองสกินรากไม้ครบทุกแบบ และธีมหน้าต่างครบทุกแบบในเกม',
    icon: '💎',
    bonusPct: 10,
    check: (s) => SKIN_DEFS.filter(def => def.id !== 'none' && !isSkinUnlocked(s, def.id)).length === 0 && UI_THEME_DEFS.filter(t => t.id !== 'classic' && !isUIThemeUnlocked(s, t.id)).length === 0,
  },

  // ===== ⏳ หมวด 6: เวลา & ความผูกพัน (Dedication & Time) =====
  {
    id: 'playtime_10m',
    category: 'time',
    title: 'รดน้ำอย่างใจเย็น',
    desc: 'เวลาเล่นสะสมรวมครบ 10 นาที',
    icon: '⏱️',
    bonusPct: 1,
    check: (s) => s.totalPlayTimeSeconds >= 600,
  },
  {
    id: 'playtime_1h',
    category: 'time',
    title: 'ผู้เฝ้ามองราก',
    desc: 'เวลาเล่นสะสมรวมครบ 1 ชั่วโมง',
    icon: '⏳',
    bonusPct: 3,
    check: (s) => s.totalPlayTimeSeconds >= 3600,
  },
  {
    id: 'playtime_12h',
    category: 'time',
    title: 'ป่าไม้ตลอดกาล',
    desc: 'เวลาเล่นสะสมรวมครบ 12 ชั่วโมง',
    icon: '🏆',
    bonusPct: 7,
    check: (s) => s.totalPlayTimeSeconds >= 43200,
  },
  {
    id: 'playtime_24h',
    category: 'time',
    title: 'ผู้พิทักษ์ผืนป่า',
    desc: 'เวลาเล่นสะสมรวมครบ 24 ชั่วโมง (1 วันเต็ม)',
    icon: '🛡️',
    bonusPct: 10,
    check: (s) => s.totalPlayTimeSeconds >= 86400,
  },
  {
    id: 'offline_1h',
    category: 'time',
    title: 'กลับมาดูแล',
    desc: 'เก็บผลผลิตออฟไลน์ (Offline Gain) ที่หายไปเกิน 1 ชั่วโมง',
    icon: '🏡',
    bonusPct: 2,
    check: (s) => (s.stats?.maxOfflineTimeSeconds || 0) >= 3600,
  },
  {
    id: 'offline_24h',
    category: 'time',
    title: 'การหลับใหลอันยาวนาน',
    desc: 'เก็บผลผลิตออฟไลน์ (Offline Gain) ที่หายไปเกิน 24 ชั่วโมง',
    icon: '💤',
    bonusPct: 8,
    check: (s) => (s.stats?.maxOfflineTimeSeconds || 0) >= 86400,
  },

  // ===== 🏺 หมวด 7: โบราณวัตถุ & ชีวนิเวศ (Relics & Biomes) =====
  {
    id: 'relic_1',
    category: 'relics',
    title: 'ขุดพบโบราณคดีชิ้นแรก',
    desc: 'ค้นพบโบราณวัตถุใต้พิภพชิ้นแรก (ครอบครอง 1/1 Master Relic 1 ชิ้น)',
    icon: '🏺',
    bonusPct: 2,
    check: (s) => relicsCount(s) >= 1,
  },
  {
    id: 'relic_5',
    category: 'relics',
    title: 'นักสำรวจอารยธรรมโบราณ',
    desc: 'ครอบครองโบราณวัตถุระดับ Master สะสมครบ 5 ชิ้น',
    icon: '📜',
    bonusPct: 5,
    check: (s) => relicsCount(s) >= 5,
  },
  {
    id: 'relic_10',
    category: 'relics',
    title: 'ผู้ครอบครองวัตถุบรรพกาล',
    desc: 'ครอบครองโบราณวัตถุใต้พิภพครบทั้ง 10 ชิ้นสมบูรณ์',
    icon: '🏛️',
    bonusPct: 10,
    check: (s) => relicsCount(s) >= 10,
  },
  {
    id: 'relic_gaiacore',
    category: 'relics',
    title: 'หัวใจแห่งไกอาตื่นรู้',
    desc: 'ค้นพบ [👑 หัวใจแห่งไกอา] โบราณวัตถุระดับ Mythic (ปลุกพลัง ×2 ทุกชิ้น)',
    icon: '👑',
    bonusPct: 10,
    check: (s) => hasRelic(s, 'gaiacore'),
  },
  {
    id: 'cycle_resonance_50',
    category: 'relics',
    title: 'พลังการเวียนว่ายครึ่งทาง',
    desc: 'สะสมพลังการเวียนว่าย (Cycle Resonance Stack) จากศิลาแก่นเพลิงพิภพแตะ +50%',
    icon: '🔥',
    bonusPct: 5,
    check: (s) => relicCycleResonanceStack(s) >= 50,
  },
  {
    id: 'cycle_resonance_100',
    category: 'relics',
    title: 'เสียงสะท้อนแห่งวัฏสงสารสูงสุด',
    desc: 'สะสมพลังการเวียนว่าย (Cycle Resonance Stack) แตะขีดจำกัดสูงสุด (≥100%)',
    icon: '🌋',
    bonusPct: 10,
    check: (s) => relicCycleResonanceStack(s) >= 100,
  },
  {
    id: 'biome_switch',
    category: 'relics',
    title: 'ก้าวสู่ถิ่นฐานใหม่',
    desc: 'สลับไปใช้ชีวนิเวศใต้พิภพอื่นที่ไม่ใช่ผิวดินชั้นบนเป็นครั้งแรก',
    icon: '🧭',
    bonusPct: 2,
    check: (s) => !!s.activeBiome && s.activeBiome !== 'topsoil',
  },
  {
    id: 'biome_sanctum',
    category: 'relics',
    title: 'สู่วิหารแห่งไกอา',
    desc: 'ปลดล็อกและเปิดใช้งานชีวนิเวศระดับสูงสุด [🌌 วิหารแห่งไกอา]',
    icon: '🌌',
    bonusPct: 8,
    check: (s) => s.activeBiome === 'gaia_sanctum',
  },

  // ===== 🌍 หมวด 8: การตื่นรู้ & การทดลอง (Transcendence & Trials) =====
  {
    id: 'transcend_1',
    category: 'gaia',
    title: 'การตื่นรู้ของพฤกษา',
    desc: 'ทำการตื่นรู้แห่งไกอา (Grand Reset) สำเร็จครั้งแรก',
    icon: '🌍',
    bonusPct: 5,
    check: (s) => (s.transcendence?.count || 0) >= 1,
  },
  {
    id: 'transcend_5',
    category: 'gaia',
    title: 'จิตวิญญาณแห่งผืนพิภพ',
    desc: 'ทำการตื่นรู้แห่งไกอาสะสมครบ 5 ครั้ง',
    icon: '🌟',
    bonusPct: 10,
    check: (s) => (s.transcendence?.count || 0) >= 5,
  },
  {
    id: 'gaia_essences_50',
    category: 'gaia',
    title: 'ประกายชีวิตดึกดำบรรพ์',
    desc: 'ครอบครองละอองชีวิตดึกดำบรรพ์ (Gaia Essences) อย่างน้อย 50 ละออง',
    icon: '✨',
    bonusPct: 3,
    check: (s) => (s.transcendence?.gaiaEssences || 0) >= 50 || (s.transcendence?.totalGaiaEssencesLifetime || 0) >= 50,
  },
  {
    id: 'gaia_essences_500',
    category: 'gaia',
    title: 'คลังพลังงานแห่งไกอา',
    desc: 'ครอบครองละอองชีวิตดึกดำบรรพ์ (Gaia Essences) สะสมอย่างน้อย 500 ละออง',
    icon: '🪐',
    bonusPct: 7,
    check: (s) => (s.transcendence?.gaiaEssences || 0) >= 500 || (s.transcendence?.totalGaiaEssencesLifetime || 0) >= 500,
  },
  {
    id: 'gaia_essences_2500',
    category: 'gaia',
    title: 'มหาสมุทรวิญญาณแห่งโลก',
    desc: 'ครอบครองละอองชีวิตดึกดำบรรพ์ (Gaia Essences) สะสมอย่างน้อย 2,500 ละออง',
    icon: '🌌',
    bonusPct: 12,
    check: (s) => (s.transcendence?.gaiaEssences || 0) >= 2500 || (s.transcendence?.totalGaiaEssencesLifetime || 0) >= 2500,
  },
  {
    id: 'transcend_vigor_max',
    category: 'gaia',
    title: 'กายาปฐมกาลไร้เทียมทาน',
    desc: 'อัพเกรดแกนพลังปฐมกาล (Primordial Vigor) แตะเลเวล 20 (สูงสุด)',
    icon: '⚡',
    bonusPct: 8,
    check: (s) => (s.transcendence?.primordialVigorLevel || 0) >= 20,
  },
  {
    id: 'transcend_soil_memory_max',
    category: 'gaia',
    title: 'ความทรงจำผืนดิน 100%',
    desc: 'อัพเกรดความทรงจำของผืนดิน (Soil Memory) แตะเลเวล 10 (คง Echoes ไว้ 100%)',
    icon: '🧠',
    bonusPct: 8,
    check: (s) => (s.transcendence?.soilMemoryLevel || 0) >= 10,
  },
  {
    id: 'trial_first_clear',
    category: 'gaia',
    title: 'ผู้ก้าวข้ามการทดสอบ',
    desc: 'พิชิตการทดลองแห่งผืนพิภพสำเร็จเป็นครั้งแรก (ปลูกต้นไม้โลกครบ 25 ต้นภายใต้ข้อจำกัด)',
    icon: '⚔️',
    bonusPct: 5,
    check: (s) => Object.keys(s.transcendence?.completedTrials || {}).length >= 1,
  },
  {
    id: 'trial_arid_drought',
    category: 'gaia',
    title: 'ผู้พิชิตแดนกันดาร',
    desc: 'พิชิตการทดลอง [🏜️ ดินแล้งกันดาร] สำเร็จ (ปลูกรากต้นไม้โลกครบ 25 ต้น)',
    icon: '🏜️',
    bonusPct: 6,
    check: (s) => !!s.transcendence?.completedTrials?.arid_drought,
  },
  {
    id: 'trial_basalt_strata',
    category: 'gaia',
    title: 'ผู้ทะลวงหินอัคนี',
    desc: 'พิชิตการทดลอง [🌋 ชั้นหินอัคนีทึบ] สำเร็จ (ปลูกรากต้นไม้โลกครบ 25 ต้น)',
    icon: '🌋',
    bonusPct: 6,
    check: (s) => !!s.transcendence?.completedTrials?.basalt_strata,
  },
  {
    id: 'trial_void_anomaly',
    category: 'gaia',
    title: 'ผู้พิชิตมิติสูญญะ',
    desc: 'พิชิตการทดลอง [🌌 รอยแยกสูญญะ] สำเร็จ โดยไม่พึ่งพาระบบบอทอัตโนมัติ',
    icon: '🌌',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.completedTrials?.void_anomaly,
  },
  {
    id: 'trial_null_cycle',
    category: 'gaia',
    title: 'ผู้พิชิตวงจรศูนย์',
    desc: 'พิชิตการทดลอง [🌑 วงจรศูนย์] สำเร็จ โดยปราศจากโบนัสเรทจาก Prestige',
    icon: '🌑',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.completedTrials?.null_cycle,
  },
  {
    id: 'trial_permafrost',
    category: 'gaia',
    title: 'ผู้ฝ่าพายุเหมันต์',
    desc: 'พิชิตการทดลอง [❄️ เหมันต์เยือกแข็ง] สำเร็จ ท่ามกลางสภาพอากาศหนาวเหน็บ',
    icon: '❄️',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.completedTrials?.permafrost,
  },
  {
    id: 'trial_geomagnetic_storm',
    category: 'gaia',
    title: 'ผู้ต้านพายุแม่เหล็ก',
    desc: 'พิชิตการทดลอง [⚡ พายุสนามแม่เหล็ก] สำเร็จ โดยปราศจากพลังสะท้อนของ Echo',
    icon: '⚡',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.completedTrials?.geomagnetic_storm,
  },
  {
    id: 'trial_all_conquered',
    category: 'gaia',
    title: 'ราชันย์ผู้พิชิตใต้พิภพ',
    desc: 'พิชิตบททดสอบแห่งผืนพิภพครบทั้ง 6 ด่านสมบูรณ์แบบ',
    icon: '👑',
    bonusPct: 20,
    check: (s) =>
      !!s.transcendence?.completedTrials?.arid_drought &&
      !!s.transcendence?.completedTrials?.basalt_strata &&
      !!s.transcendence?.completedTrials?.void_anomaly &&
      !!s.transcendence?.completedTrials?.null_cycle &&
      !!s.transcendence?.completedTrials?.permafrost &&
      !!s.transcendence?.completedTrials?.geomagnetic_storm,
  },
  {
    id: 'gaia_touch_max',
    category: 'gaia',
    title: 'หัตถ์แห่งเทพพิภพ',
    desc: 'อัพเกรดสัมผัสแห่งไกอา (Gaia Touch) แตะเลเวล 10 (สูงสุด)',
    icon: '✨',
    bonusPct: 8,
    check: (s) => (s.transcendence?.gaiaTouchLevel || 0) >= 10,
  },
  {
    id: 'echo_resonance_max',
    category: 'gaia',
    title: 'กังวานคลื่นไร้ขีดจำกัด',
    desc: 'อัพเกรดความกังวานแห่งเสียงสะท้อน (Echo Resonance) แตะเลเวล 5 (สูงสุด)',
    icon: '🔔',
    bonusPct: 7,
    check: (s) => (s.transcendence?.echoResonanceLevel || 0) >= 5,
  },
  {
    id: 'primordial_seedling_max',
    category: 'gaia',
    title: 'พงไพรจากเศษดิน',
    desc: 'อัพเกรดต้นกล้าปฐมกาล (Primordial Seedling) แตะเลเวล 5 (สูงสุด)',
    icon: '🌱',
    bonusPct: 7,
    check: (s) => (s.transcendence?.primordialSeedlingLevel || 0) >= 5,
  },
  {
    id: 'gaia_meditation_max',
    category: 'gaia',
    title: 'สมาธิลึกใต้พิภพ',
    desc: 'อัพเกรดสมาธิลึก (Deep Meditation) แตะเลเวล 5 (สูงสุด)',
    icon: '🧘',
    bonusPct: 8,
    check: (s) => (s.transcendence?.deepMeditationLevel || 0) >= 5,
  },
  {
    id: 'gaia_blessing_1',
    category: 'gaia',
    title: 'ก้าวข้ามขีดจำกัดแห่งไกอา',
    desc: 'อัพเกรดพรแห่งไกอา (Gaia\'s Blessing) แตะเลเวล 1',
    icon: '🌌',
    bonusPct: 5,
    check: (s) => (s.transcendence?.gaiaBlessingLevel || 0) >= 1,
  },
  {
    id: 'gaia_blessing_10',
    category: 'gaia',
    title: 'พรอันเป็นนิรันดร์',
    desc: 'อัพเกรดพรแห่งไกอาสะสมครบเลเวล 10 (+50% ละอองไกอา)',
    icon: '👑',
    bonusPct: 10,
    check: (s) => (s.transcendence?.gaiaBlessingLevel || 0) >= 10,
  },
  {
    id: 'hyperdrive_unlock',
    category: 'gaia',
    title: 'เร่งความเร็วมิติกาลเวลา',
    desc: 'ปลดล็อกตัวเร่งเวลา 2x Hyperdrive Overclock ในผังจิตวิญญาณไกอา',
    icon: '⚡',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.hyperdriveUnlocked,
  },
  {
    id: 'aurora_bloom_unlock',
    category: 'gaia',
    title: 'ปรากฏการณ์แสงเหนือใต้พิภพ',
    desc: 'ปลดล็อกออโรร่าบลูม (Aurora Bloom) เพื่อเรียกสปอร์ออโรร่าและเตาหลอมกลีบดวงดาว',
    icon: '🌸',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.auroraBloomUnlocked,
  },
  {
    id: 'gaia_clairvoyance_5',
    category: 'gaia',
    title: 'เนตรแห่งไกอา',
    desc: 'อัพเกรดสายตาแห่งไกอา (Gaia Clairvoyance) แตะเลเวล 5',
    icon: '👁️',
    bonusPct: 5,
    check: (s) => (s.transcendence?.gaiaClairvoyanceLevel || 0) >= 5,
  },
  {
    id: 'astral_petal_1',
    category: 'luck',
    title: 'ละอองกลีบดวงดาราแรก',
    desc: 'เก็บหรือหลอมกลีบดอกไม้ดวงดาว (Astral Petals) ชิ้นแรกสำเร็จ',
    icon: '🌸',
    bonusPct: 4,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 1,
  },
  {
    id: 'astral_petal_10',
    category: 'luck',
    title: 'มาลัยดอกไม้แห่งฟากฟ้า',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมอย่างน้อย 10 กลีบ',
    icon: '💐',
    bonusPct: 6,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 10,
  },
  {
    id: 'astral_petal_50',
    category: 'luck',
    title: 'สวนบุปผาดวงดารานิรันดร์',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมครบ 50 กลีบ (พร้อมแลกธีมหน้าต่างแสงเหนือ)',
    icon: '🌺',
    bonusPct: 10,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 50,
  },
  {
    id: 'astral_petal_500',
    category: 'luck',
    title: 'มหาดวงดาราคอสมิกแห่งไกอา',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมครบ 500 กลีบ (พร้อมแลกสกินระดับสูงสุด)',
    icon: '✨',
    bonusPct: 20,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 500,
  },

  // ===== 🎨 หมวด 7: สกิน & แฟชั่นใต้พิภพ (Cosmetics & Aesthetics) =====
  {
    id: 'skin_first_wardrobe',
    category: 'skins',
    title: 'อาภรณ์ชิ้นแรก',
    desc: 'ปลดล็อกสกินรากไม้หรือธีมหน้าต่างตกแต่งชิ้นแรก',
    icon: '👗',
    bonusPct: 3,
    check: (s) =>
      SKIN_DEFS.some(def => def.id !== 'none' && isSkinUnlocked(s, def.id)) ||
      UI_THEME_DEFS.some(def => def.id !== 'classic' && isUIThemeUnlocked(s, def.id)),
  },
  {
    id: 'theme_subterranean_borealis',
    category: 'skins',
    title: 'มงกุฎแสงเหนือใต้พิภพ',
    desc: 'ปลดล็อกธีมหน้าต่าง UI ระดับ Mythic [🌌 แสงเหนือใต้พิภพ (Subterranean Borealis)]',
    icon: '🌌',
    bonusPct: 6,
    check: (s) => isUIThemeUnlocked(s, 'subterranean_borealis'),
  },
  {
    id: 'skin_timeless_aurora',
    category: 'skins',
    title: 'รัตติกาลไร้กาลเวลา',
    desc: 'ปลดล็อกสกินรากไม้ระดับ Mythic [🌸 ออโรร่าไร้กาลเวลา (Timeless Aurora)]',
    icon: '🌸',
    bonusPct: 8,
    check: (s) => isSkinUnlocked(s, 'timeless_aurora'),
  },
  {
    id: 'skin_starlight_prism',
    category: 'skins',
    title: 'ปริซึมผลึกสะท้อนดวงดาว',
    desc: 'ปลดล็อกสกินรากไม้ขั้นสูงสุดระดับ Mythic [✨ ผลึกคริสตัลดวงดาว (Starlight Prism)]',
    icon: '✨',
    bonusPct: 15,
    check: (s) => isSkinUnlocked(s, 'starlight_prism'),
  },
  {
    id: 'astral_trio_collector',
    category: 'skins',
    title: 'จักรพรรดิแห่งดวงดาราและแสงเหนือ',
    desc: 'ครอบครองเครื่องประดับ Astral Mythic ครบทั้ง 3 ชิ้น (สกิน 2 แบบ + ธีม 1 แบบ)',
    icon: '👑',
    bonusPct: 20,
    check: (s) =>
      isSkinUnlocked(s, 'timeless_aurora') &&
      isSkinUnlocked(s, 'starlight_prism') &&
      isUIThemeUnlocked(s, 'subterranean_borealis'),
  },
];

export const ACHIEVEMENT_BONUS_MAP: Record<string, number> = Object.fromEntries(
  ACHIEVEMENTS.map(a => [a.id, a.bonusPct])
);

export const TOTAL_ACHIEVEMENTS = ACHIEVEMENTS.length;
