import { GameState } from '@/types/game';
import { MODULE_DEFS } from './modules';

/**
 * Creates a fresh, default GameState for new runs or hard resets.
 */
export function createFreshState(): GameState {
  const s: GameState = {
    nutrients: 0,
    owned: {},
    totalOwned: 0,
    rootUpgrades: {},
    echoes: {},
    rootSynergies: {},
    relics: {},
    unclaimedRelicId: null,
    activeBiome: 'topsoil',
    buyQty: 1,
    lockGapBackfilled: true,
    totalPlayTimeSeconds: 0,
    runPlayTimeSeconds: 0,
    runEarned: 0,
    eternalSeeds: 0,
    prestige: {
      starterLevel: 0,
      autoRoot: false,
      autoRootEnabled: false,
      autoRootMode: 'all',
      autoRootSmart: false,
      autoRootAll: false,
      goldenLevel: 0,
      auraRoots: false,
      auraRootsEnabled: false,
      skinSakura: false,
      skinCafe: false,
      skinAutumn: false,
      skinOcean: false,
      skinFrost: false,
      skinSunset: false,
      skinSameOrigin: false,
      skinMystic: false,
      skinCyberpunk: false,
      skinGrayscale: false,
      skinGradient: false,
      skinNebula: false,
      skinImperial: false,
      skinTimelessAurora: false,
      skinStarlightPrism: false,
      activeSkin: 'none',
      themeSakura: false,
      themeCafe: false,
      themeAutumn: false,
      themeOcean: false,
      themeFrost: false,
      themeSunset: false,
      themeMystic: false,
      themeCyberpunk: false,
      themeEmerald: false,
      themeNebula: false,
      themeImperial: false,
      themeSubterraneanBorealis: false,
      activeUITheme: 'classic',
      autoReset: false,
      autoResetEnabled: false,
      autoResetThreshold: 1000,
      offlineCapLevel: 0,
      eventBonusLevel: 0,
      eventDurationLevel: 0,
      autoEvent: false,
      autoEventEnabled: false,
      luckyMagnitudeLevel: 0,
      luckyDurationLevel: 0,
      luckyChanceLevel: 0,
      passiveRateLevel: 0,
    },
    transcendence: {
      count: 0,
      gaiaEssences: 0,
      totalGaiaEssencesLifetime: 0,
      primordialVigorLevel: 0,
      soilMemoryLevel: 0,
      autoManagerUnlocked: false,
      gaiaTouchLevel: 0,
      activeTrial: 'none',
      completedTrials: {},
      echoResonanceLevel: 0,
      gaiaClairvoyanceLevel: 0,
      primordialSeedlingLevel: 0,
      deepMeditationLevel: 0,
      gaiaBlessingLevel: 0,
      hyperdriveUnlocked: false,
      hyperdriveEnabled: false,
      auroraBloomUnlocked: false,
      astralPetals: 0,
    },
    pacts: {},
    achievements: [],
    stats: {
      prestigeCount: 0,
      totalEventsClaimed: 0,
      luckyJackpotCount: 0,
      maxOfflineTimeSeconds: 0,
      superJackpotClaimed: false,
      totalSeedsEarnedLifetime: 0,
      totalNutrientsEarnedLifetime: 0,
    },
    lang: 'th',
  };
  MODULE_DEFS.forEach(m => { s.owned[m.id] = 0; });
  return s;
}
