import { AchievementDef } from '@/types/achievements';

export const ECONOMY_ACHIEVEMENTS: AchievementDef[] = [
// ===== ⚡ หมวด 2: เศรษฐกิจ & ผลผลิตสารอาหาร (Economy & Rate) =====
  {
    id: 'nutrients_1k',
    category: 'economy',
    title: 'หยดน้ำสร้างป่า',
    desc: 'สะสมสารอาหารครบ 1,000 (1K)',
    icon: '💧',
    bonusPct: 1,
    check: (s) => s.nutrients >= 1000 || s.runEarned >= 1000 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1000,
  },
  {
    id: 'nutrients_1m',
    category: 'economy',
    title: 'มหาเศรษฐีผืนดิน',
    desc: 'สะสมสารอาหารครบ 1,000,000 (1M)',
    icon: '💰',
    bonusPct: 2,
    check: (s) => s.nutrients >= 1e6 || s.runEarned >= 1e6 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e6,
  },
  {
    id: 'nutrients_1b',
    category: 'economy',
    title: 'ขุมทรัพย์ใต้พิภพ',
    desc: 'สะสมสารอาหารครบ 1,000,000,000 (1B)',
    icon: '💎',
    bonusPct: 3,
    check: (s) => s.nutrients >= 1e9 || s.runEarned >= 1e9 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e9,
  },
  {
    id: 'nutrients_100b',
    category: 'economy',
    title: 'ขุมพลังมหาศาล',
    desc: 'สะสมสารอาหารครบ 100,000,000,000 (100B)',
    icon: '🔮',
    bonusPct: 4,
    check: (s) => s.nutrients >= 1e11 || s.runEarned >= 1e11 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e11,
  },
  {
    id: 'nutrients_1t',
    category: 'economy',
    title: 'ความอุดมสมบูรณ์ไร้ขีดจำกัด',
    desc: 'สะสมสารอาหารครบ 1T (Trillion)',
    icon: '🌟',
    bonusPct: 5,
    check: (s) => s.nutrients >= 1e12 || s.runEarned >= 1e12 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e12,
  },
  {
    id: 'nutrients_100t',
    category: 'economy',
    title: 'ทะเลสาบสารอาหาร',
    desc: 'สะสมสารอาหารครบ 100T (100 Trillion)',
    icon: '🌊',
    bonusPct: 6,
    check: (s) => s.nutrients >= 1e14 || s.runEarned >= 1e14 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e14,
  },
  {
    id: 'nutrients_1qa',
    category: 'economy',
    title: 'พลังแห่งจักรวาล',
    desc: 'สะสมสารอาหารครบ 1Qa (Quadrillion)',
    icon: '🌌',
    bonusPct: 7,
    check: (s) => s.nutrients >= 1e15 || s.runEarned >= 1e15 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e15,
  },
  {
    id: 'nutrients_100qa',
    category: 'economy',
    title: 'มหาสมุทรแห่งชีวิต',
    desc: 'สะสมสารอาหารครบ 100Qa (100 Quadrillion)',
    icon: '🪐',
    bonusPct: 8,
    check: (s) => s.nutrients >= 1e17 || s.runEarned >= 1e17 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e17,
  },
  {
    id: 'nutrients_1qi',
    category: 'economy',
    title: 'แก่นแท้แห่งสรรพสิ่ง',
    desc: 'สะสมสารอาหารครบ 1Qi (Quintillion)',
    icon: '☀️',
    bonusPct: 9,
    check: (s) => s.nutrients >= 1e18 || s.runEarned >= 1e18 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e18,
  },
  {
    id: 'nutrients_1sx',
    category: 'economy',
    title: 'กำเนิดจักรวาลใหม่',
    desc: 'สะสมสารอาหารครบ 1Sx (Sextillion)',
    icon: '💫',
    bonusPct: 10,
    check: (s) => s.nutrients >= 1e21 || s.runEarned >= 1e21 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e21,
  },
  {
    id: 'nutrients_1sp',
    category: 'economy',
    title: 'มหันตภัยสารอาหาร',
    desc: 'สะสมสารอาหารครบ 1Sp (Septillion)',
    icon: '🪐',
    bonusPct: 10,
    check: (s) => s.nutrients >= 1e24 || s.runEarned >= 1e24 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e24,
  },
  {
    id: 'nutrients_1oc',
    category: 'economy',
    title: 'ขุมพลังไร้ที่สิ้นสุด',
    desc: 'สะสมสารอาหารครบ 1Oc (Octillion)',
    icon: '👑',
    bonusPct: 10,
    check: (s) => s.nutrients >= 1e27 || s.runEarned >= 1e27 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e27,
  },
  {
    id: 'nutrients_1no',
    category: 'economy',
    title: 'มหาพิภพไร้ขอบเขต',
    desc: 'สะสมสารอาหารครบ 1No (Nonillion)',
    icon: '🪐',
    bonusPct: 10,
    check: (s) => s.nutrients >= 1e30 || s.runEarned >= 1e30 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e30,
  },
  {
    id: 'nutrients_1dc',
    category: 'economy',
    title: 'แก่นสารอาหารจักรวาล',
    desc: 'สะสมสารอาหารครบ 1Dc (Decillion)',
    icon: '🔮',
    bonusPct: 12,
    check: (s) => s.nutrients >= 1e33 || s.runEarned >= 1e33 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e33,
  },
  {
    id: 'nutrients_1udc',
    category: 'economy',
    title: 'มหาสมุทรพลังงานอนันต์',
    desc: 'สะสมสารอาหารครบ 1UDc (Undecillion)',
    icon: '🌌',
    bonusPct: 15,
    check: (s) => s.nutrients >= 1e36 || s.runEarned >= 1e36 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e36,
  },
  {
    id: 'nutrients_1qadc',
    category: 'economy',
    title: 'พฤกษากลืนมิติเวลา',
    desc: 'สะสมสารอาหารครบ 1QaDc (Quattuordecillion)',
    icon: '⏳',
    bonusPct: 18,
    check: (s) => s.nutrients >= 1e45 || s.runEarned >= 1e45 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e45,
  },
  {
    id: 'nutrients_1vg',
    category: 'economy',
    title: 'ผู้สร้างจักรวาลปฐมกาล',
    desc: 'สะสมสารอาหารครบ 1Vg (Vigintillion)',
    icon: '👑',
    bonusPct: 20,
    check: (s) => s.nutrients >= 1e63 || s.runEarned >= 1e63 || (s.stats?.totalNutrientsEarnedLifetime || 0) >= 1e63,
  },
  {
    id: 'rate_10k',
    category: 'economy',
    title: 'เร่งฝีเท้า',
    desc: 'ผลิตสารอาหารเกิน 10,000 / วินาที',
    icon: '⚡',
    bonusPct: 1,
    check: (_, rate) => rate >= 10000,
  },
  {
    id: 'rate_10m',
    category: 'economy',
    title: 'น้ำตกสารอาหาร',
    desc: 'ผลิตสารอาหารเกิน 10,000,000 / วินาที',
    icon: '🌊',
    bonusPct: 3,
    check: (_, rate) => rate >= 1e7,
  },
  {
    id: 'rate_100b',
    category: 'economy',
    title: 'พลังไหลบ่า',
    desc: 'ผลิตสารอาหารเกิน 100,000,000,000 / วินาที (100B/วิ)',
    icon: '🔥',
    bonusPct: 5,
    check: (_, rate) => rate >= 1e11,
  },
  {
    id: 'rate_1t',
    category: 'economy',
    title: 'มหาวาตภัยสารอาหาร',
    desc: 'ผลิตสารอาหารเกิน 1,000,000,000,000 / วินาที (1T/วิ)',
    icon: '🌪️',
    bonusPct: 7,
    check: (_, rate) => rate >= 1e12,
  },
  {
    id: 'rate_1qa',
    category: 'economy',
    title: 'ดัชนีการเติบโตระดับดวงดาว',
    desc: 'ผลิตสารอาหารเกิน 1Qa / วินาที (Quadrillion/วิ)',
    icon: '🌠',
    bonusPct: 8,
    check: (_, rate) => rate >= 1e15,
  },
  {
    id: 'rate_1qi',
    category: 'economy',
    title: 'พลังขับเคลื่อนแห่งอนันต์',
    desc: 'ผลิตสารอาหารเกิน 1Qi / วินาที (Quintillion/วิ)',
    icon: '🌌',
    bonusPct: 9,
    check: (_, rate) => rate >= 1e18,
  },
  {
    id: 'rate_1sx',
    category: 'economy',
    title: 'คลื่นพลังเซกทิลเลียน',
    desc: 'ผลิตสารอาหารเกิน 1Sx / วินาที (Sextillion/วิ)',
    icon: '⚡',
    bonusPct: 10,
    check: (_, rate) => rate >= 1e21,
  },
  {
    id: 'rate_1sp',
    category: 'economy',
    title: 'อัตราการเติบโตระดับดาราจักร',
    desc: 'ผลิตสารอาหารเกิน 1Sp / วินาที (Septillion/วิ)',
    icon: '🌌',
    bonusPct: 10,
    check: (_, rate) => rate >= 1e24,
  },
  {
    id: 'rate_1oc',
    category: 'economy',
    title: 'การระเบิดแห่งบิ๊กแบง',
    desc: 'ผลิตสารอาหารเกิน 1Oc / วินาที (Octillion/วิ)',
    icon: '💥',
    bonusPct: 12,
    check: (_, rate) => rate >= 1e27,
  },
  {
    id: 'rate_1no',
    category: 'economy',
    title: 'อัตราเร่งแห่งเอกภพ',
    desc: 'ผลิตสารอาหารเกิน 1No / วินาที (Nonillion/วิ)',
    icon: '🪐',
    bonusPct: 15,
    check: (_, rate) => rate >= 1e30,
  },
  {
    id: 'rate_1dc',
    category: 'economy',
    title: 'มหาพฤกษาเหนือจักรวาล',
    desc: 'ผลิตสารอาหารเกิน 1Dc / วินาที (Decillion/วิ)',
    icon: '🌟',
    bonusPct: 20,
    check: (_, rate) => rate >= 1e33,
  },
];
