import { AchievementDef } from '@/types/achievements';

export const GAIA_ACHIEVEMENTS: AchievementDef[] = [
// ===== 🌍 หมวด 8: การตื่นรู้ & การทดลอง (Transcendence & Trials) =====
  {
    id: 'transcend_1',
    category: 'gaia',
    title: 'การตื่นรู้ของพฤกษา',
    desc: 'ทำการตื่นรู้แห่งไกอา (Grand Reset) สำเร็จครั้งแรก',
    icon: '🌍',
    bonusPct: 5,
    check: (s) => (s.transcendence?.count || 0) >= 1,
  },
  {
    id: 'transcend_5',
    category: 'gaia',
    title: 'จิตวิญญาณแห่งผืนพิภพ',
    desc: 'ทำการตื่นรู้แห่งไกอาสะสมครบ 5 ครั้ง',
    icon: '🌟',
    bonusPct: 10,
    check: (s) => (s.transcendence?.count || 0) >= 5,
  },
  {
    id: 'gaia_essences_50',
    category: 'gaia',
    title: 'ประกายชีวิตดึกดำบรรพ์',
    desc: 'ครอบครองละอองชีวิตดึกดำบรรพ์ (Gaia Essences) อย่างน้อย 50 ละออง',
    icon: '✨',
    bonusPct: 3,
    check: (s) => (s.transcendence?.gaiaEssences || 0) >= 50 || (s.transcendence?.totalGaiaEssencesLifetime || 0) >= 50,
  },
  {
    id: 'gaia_essences_500',
    category: 'gaia',
    title: 'คลังพลังงานแห่งไกอา',
    desc: 'ครอบครองละอองชีวิตดึกดำบรรพ์ (Gaia Essences) สะสมอย่างน้อย 500 ละออง',
    icon: '🪐',
    bonusPct: 7,
    check: (s) => (s.transcendence?.gaiaEssences || 0) >= 500 || (s.transcendence?.totalGaiaEssencesLifetime || 0) >= 500,
  },
  {
    id: 'gaia_essences_2500',
    category: 'gaia',
    title: 'มหาสมุทรวิญญาณแห่งโลก',
    desc: 'ครอบครองละอองชีวิตดึกดำบรรพ์ (Gaia Essences) สะสมอย่างน้อย 2,500 ละออง',
    icon: '🌌',
    bonusPct: 12,
    check: (s) => (s.transcendence?.gaiaEssences || 0) >= 2500 || (s.transcendence?.totalGaiaEssencesLifetime || 0) >= 2500,
  },
  {
    id: 'transcend_vigor_max',
    category: 'gaia',
    title: 'กายาปฐมกาลไร้เทียมทาน',
    desc: 'อัพเกรดแกนพลังปฐมกาล (Primordial Vigor) แตะเลเวล 20 (สูงสุด)',
    icon: '⚡',
    bonusPct: 8,
    check: (s) => (s.transcendence?.primordialVigorLevel || 0) >= 20,
  },
  {
    id: 'transcend_soil_memory_max',
    category: 'gaia',
    title: 'ความทรงจำผืนดิน 100%',
    desc: 'อัพเกรดความทรงจำของผืนดิน (Soil Memory) แตะเลเวล 10 (คง Echoes ไว้ 100%)',
    icon: '🧠',
    bonusPct: 8,
    check: (s) => (s.transcendence?.soilMemoryLevel || 0) >= 10,
  },
  {
    id: 'trial_first_clear',
    category: 'gaia',
    title: 'ผู้ก้าวข้ามการทดสอบ',
    desc: 'พิชิตการทดลองแห่งผืนพิภพสำเร็จเป็นครั้งแรก (ปลูกต้นไม้โลกครบ 25 ต้นภายใต้ข้อจำกัด)',
    icon: '⚔️',
    bonusPct: 5,
    check: (s) => Object.keys(s.transcendence?.completedTrials || {}).length >= 1,
  },
  {
    id: 'trial_arid_drought',
    category: 'gaia',
    title: 'ผู้พิชิตแดนกันดาร',
    desc: 'พิชิตการทดลอง [🏜️ ดินแล้งกันดาร] สำเร็จ (ปลูกรากต้นไม้โลกครบ 25 ต้น)',
    icon: '🏜️',
    bonusPct: 6,
    check: (s) => !!s.transcendence?.completedTrials?.arid_drought,
  },
  {
    id: 'trial_basalt_strata',
    category: 'gaia',
    title: 'ผู้ทะลวงหินอัคนี',
    desc: 'พิชิตการทดลอง [🌋 ชั้นหินอัคนีทึบ] สำเร็จ (ปลูกรากต้นไม้โลกครบ 25 ต้น)',
    icon: '🌋',
    bonusPct: 6,
    check: (s) => !!s.transcendence?.completedTrials?.basalt_strata,
  },
  {
    id: 'trial_void_anomaly',
    category: 'gaia',
    title: 'ผู้พิชิตมิติสูญญะ',
    desc: 'พิชิตการทดลอง [🌌 รอยแยกสูญญะ] สำเร็จ โดยไม่พึ่งพาระบบบอทอัตโนมัติ',
    icon: '🌌',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.completedTrials?.void_anomaly,
  },
  {
    id: 'trial_null_cycle',
    category: 'gaia',
    title: 'ผู้พิชิตวงจรศูนย์',
    desc: 'พิชิตการทดลอง [🌑 วงจรศูนย์] สำเร็จ โดยปราศจากโบนัสเรทจาก Prestige',
    icon: '🌑',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.completedTrials?.null_cycle,
  },
  {
    id: 'trial_permafrost',
    category: 'gaia',
    title: 'ผู้ฝ่าพายุเหมันต์',
    desc: 'พิชิตการทดลอง [❄️ เหมันต์เยือกแข็ง] สำเร็จ ท่ามกลางสภาพอากาศหนาวเหน็บ',
    icon: '❄️',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.completedTrials?.permafrost,
  },
  {
    id: 'trial_geomagnetic_storm',
    category: 'gaia',
    title: 'ผู้ต้านพายุแม่เหล็ก',
    desc: 'พิชิตการทดลอง [⚡ พายุสนามแม่เหล็ก] สำเร็จ โดยปราศจากพลังสะท้อนของ Echo',
    icon: '⚡',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.completedTrials?.geomagnetic_storm,
  },
  {
    id: 'trial_all_conquered',
    category: 'gaia',
    title: 'ราชันย์ผู้พิชิตใต้พิภพ',
    desc: 'พิชิตบททดสอบแห่งผืนพิภพครบทั้ง 6 ด่านสมบูรณ์แบบ',
    icon: '👑',
    bonusPct: 20,
    check: (s) =>
      !!s.transcendence?.completedTrials?.arid_drought &&
      !!s.transcendence?.completedTrials?.basalt_strata &&
      !!s.transcendence?.completedTrials?.void_anomaly &&
      !!s.transcendence?.completedTrials?.null_cycle &&
      !!s.transcendence?.completedTrials?.permafrost &&
      !!s.transcendence?.completedTrials?.geomagnetic_storm,
  },
  {
    id: 'gaia_touch_max',
    category: 'gaia',
    title: 'หัตถ์แห่งเทพพิภพ',
    desc: 'อัพเกรดสัมผัสแห่งไกอา (Gaia Touch) แตะเลเวล 10 (สูงสุด)',
    icon: '✨',
    bonusPct: 8,
    check: (s) => (s.transcendence?.gaiaTouchLevel || 0) >= 10,
  },
  {
    id: 'echo_resonance_max',
    category: 'gaia',
    title: 'กังวานคลื่นไร้ขีดจำกัด',
    desc: 'อัพเกรดความกังวานแห่งเสียงสะท้อน (Echo Resonance) แตะเลเวล 5 (สูงสุด)',
    icon: '🔔',
    bonusPct: 7,
    check: (s) => (s.transcendence?.echoResonanceLevel || 0) >= 5,
  },
  {
    id: 'primordial_seedling_max',
    category: 'gaia',
    title: 'พงไพรจากเศษดิน',
    desc: 'อัพเกรดต้นกล้าปฐมกาล (Primordial Seedling) แตะเลเวล 5 (สูงสุด)',
    icon: '🌱',
    bonusPct: 7,
    check: (s) => (s.transcendence?.primordialSeedlingLevel || 0) >= 5,
  },
  {
    id: 'gaia_meditation_max',
    category: 'gaia',
    title: 'สมาธิลึกใต้พิภพ',
    desc: 'อัพเกรดสมาธิลึก (Deep Meditation) แตะเลเวล 5 (สูงสุด)',
    icon: '🧘',
    bonusPct: 8,
    check: (s) => (s.transcendence?.deepMeditationLevel || 0) >= 5,
  },
  {
    id: 'gaia_blessing_1',
    category: 'gaia',
    title: 'ก้าวข้ามขีดจำกัดแห่งไกอา',
    desc: 'อัพเกรดพรแห่งไกอา (Gaia\'s Blessing) แตะเลเวล 1',
    icon: '🌌',
    bonusPct: 5,
    check: (s) => (s.transcendence?.gaiaBlessingLevel || 0) >= 1,
  },
  {
    id: 'gaia_blessing_10',
    category: 'gaia',
    title: 'พรอันเป็นนิรันดร์',
    desc: 'อัพเกรดพรแห่งไกอาสะสมครบเลเวล 10 (+50% ละอองไกอา)',
    icon: '👑',
    bonusPct: 10,
    check: (s) => (s.transcendence?.gaiaBlessingLevel || 0) >= 10,
  },
  {
    id: 'hyperdrive_unlock',
    category: 'gaia',
    title: 'เร่งความเร็วมิติกาลเวลา',
    desc: 'ปลดล็อกตัวเร่งเวลา 2x Hyperdrive Overclock ในผังจิตวิญญาณไกอา',
    icon: '⚡',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.hyperdriveUnlocked,
  },
  {
    id: 'aurora_bloom_unlock',
    category: 'gaia',
    title: 'ปรากฏการณ์แสงเหนือใต้พิภพ',
    desc: 'ปลดล็อกออโรร่าบลูม (Aurora Bloom) เพื่อเรียกสปอร์ออโรร่าและเตาหลอมกลีบดวงดาว',
    icon: '🌸',
    bonusPct: 8,
    check: (s) => !!s.transcendence?.auroraBloomUnlocked,
  },
  {
    id: 'gaia_clairvoyance_5',
    category: 'gaia',
    title: 'เนตรแห่งไกอา',
    desc: 'อัพเกรดสายตาแห่งไกอา (Gaia Clairvoyance) แตะเลเวล 5',
    icon: '👁️',
    bonusPct: 5,
    check: (s) => (s.transcendence?.gaiaClairvoyanceLevel || 0) >= 5,
  },
  {
    id: 'astral_petal_1',
    category: 'luck',
    title: 'ละอองกลีบดวงดาราแรก',
    desc: 'เก็บหรือหลอมกลีบดอกไม้ดวงดาว (Astral Petals) ชิ้นแรกสำเร็จ',
    icon: '🌸',
    bonusPct: 4,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 1,
  },
  {
    id: 'astral_petal_10',
    category: 'luck',
    title: 'มาลัยดอกไม้แห่งฟากฟ้า',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมอย่างน้อย 10 กลีบ',
    icon: '💐',
    bonusPct: 6,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 10,
  },
  {
    id: 'astral_petal_50',
    category: 'luck',
    title: 'สวนบุปผาดวงดารานิรันดร์',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมครบ 50 กลีบ (พร้อมแลกธีมหน้าต่างแสงเหนือ)',
    icon: '🌺',
    bonusPct: 10,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 50,
  },
  {
    id: 'astral_petal_500',
    category: 'luck',
    title: 'มหาดวงดาราคอสมิกแห่งไกอา',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมครบ 500 กลีบ (พร้อมแลกสกินระดับสูงสุด)',
    icon: '✨',
    bonusPct: 20,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 500,
  },
];
