import { AchievementDef } from '@/types/achievements';

export const LUCK_ACHIEVEMENTS: AchievementDef[] = [
// ===== 🍀 หมวด 4: โชคชะตา & เหตุการณ์พิเศษ (Luck & Events) =====
  {
    id: 'event_1',
    category: 'luck',
    title: 'ตาไวคว้าทัน',
    desc: 'คลิกเก็บอีเวนต์บนจอครั้งแรก',
    icon: '🎯',
    bonusPct: 1,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 1,
  },
  {
    id: 'event_25',
    category: 'luck',
    title: 'นักล่าสมบัติ',
    desc: 'เก็บอีเวนต์สะสมครบ 25 ครั้ง',
    icon: '🎁',
    bonusPct: 3,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 25,
  },
  {
    id: 'event_100',
    category: 'luck',
    title: 'ผู้ไม่เคยพลาด',
    desc: 'เก็บอีเวนต์สะสมครบ 100 ครั้ง',
    icon: '⚡',
    bonusPct: 6,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 100,
  },
  {
    id: 'event_500',
    category: 'luck',
    title: 'มือเก็บเกี่ยวแห่งตำนาน',
    desc: 'เก็บอีเวนต์สะสมครบ 500 ครั้ง',
    icon: '🌠',
    bonusPct: 10,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 500,
  },
  {
    id: 'lucky_1',
    category: 'luck',
    title: 'แจ็กพอตแห่งโชคชะตา',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) ครั้งแรก',
    icon: '🍀',
    bonusPct: 5,
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 1,
  },
  {
    id: 'lucky_10',
    category: 'luck',
    title: 'เทพแห่งโชคลาภ',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) สะสมครบ 10 ครั้ง',
    icon: '🎲',
    bonusPct: 10,
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 10,
  },
  {
    id: 'super_jackpot',
    category: 'luck',
    title: 'แจ็กพอตซ้อนแจ็กพอต',
    desc: 'เก็บกล่อง 🎁 ได้รับสารอาหารก้อนโตขณะมีบัฟโชคดีทำงานอยู่',
    icon: '💥',
    bonusPct: 10,
    check: (s) => s.stats?.superJackpotClaimed === true,
  },
  {
    id: 'event_bonus_25',
    category: 'luck',
    title: 'ผลตอบแทนงอกเงย',
    desc: 'อัพเกรดโบนัสอีเวนต์ (Event Value Booster) ในร้านหว่านใหม่แตะเลเวล 25',
    icon: '🎁',
    bonusPct: 3,
    check: (s) => (s.prestige.eventBonusLevel || 0) >= 25,
  },
  {
    id: 'event_duration_max',
    category: 'luck',
    title: 'เวลาแห่งบัฟ',
    desc: 'อัพเกรดขยายระยะเวลาบัฟอีเวนต์แตะเลเวล 4 (สูงสุด)',
    icon: '⏳',
    bonusPct: 4,
    check: (s) => (s.prestige.eventDurationLevel || 0) >= 4,
  },
  {
    id: 'lucky_chance_max',
    category: 'luck',
    title: 'ทุ่งโคลเวอร์เบ่งบาน',
    desc: 'อัพเกรดโอกาสพบเจอโชคดีแตะเลเวล 8 (สูงสุด 1.0%)',
    icon: '🍀',
    bonusPct: 5,
    check: (s) => (s.prestige.luckyChanceLevel || 0) >= 8,
  },
  {
    id: 'lucky_magnitude_max',
    category: 'luck',
    title: 'โชคดีสิบเท่าทวีคูณ',
    desc: 'อัพเกรดโชคดีทวีคูณแตะเลเวล 9 (สูงสุด ทบตัวคูณโชคดี ×10)',
    icon: '🎲',
    bonusPct: 5,
    check: (s) => (s.prestige.luckyMagnitudeLevel || 0) >= 9,
  },
];
