import { AchievementDef } from '@/types/achievements';

export const LUCK_ACHIEVEMENTS: AchievementDef[] = [
// ===== 🍀 หมวด 4: โชคชะตา & เหตุการณ์พิเศษ (Luck & Events) =====
  // --- กล่องอีเวนต์สุ่ม (Floating Events) ---
  {
    id: 'event_1',
    category: 'luck',
    title: 'ตาไวคว้าทัน',
    desc: 'คลิกเก็บอีเวนต์บนจอครั้งแรก',
    icon: '🎯',
    bonusPct: 1,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 1,
  },
  {
    id: 'event_25',
    category: 'luck',
    title: 'นักล่าสมบัติ',
    desc: 'เก็บอีเวนต์สะสมครบ 25 ครั้ง',
    icon: '🎁',
    bonusPct: 3,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 25,
  },
  {
    id: 'event_100',
    category: 'luck',
    title: 'ผู้ไม่เคยพลาด',
    desc: 'เก็บอีเวนต์สะสมครบ 100 ครั้ง',
    icon: '⚡',
    bonusPct: 6,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 100,
  },
  {
    id: 'event_500',
    category: 'luck',
    title: 'มือเก็บเกี่ยวแห่งตำนาน',
    desc: 'เก็บอีเวนต์สะสมครบ 500 ครั้ง',
    icon: '🌠',
    bonusPct: 10,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 500,
  },
  {
    id: 'event_1500',
    category: 'luck',
    title: 'ปรมาจารย์นักคว้าโอกาส',
    desc: 'เก็บอีเวนต์สะสมครบ 1,500 ครั้ง',
    icon: '🌌',
    bonusPct: 18,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 1500,
  },
  {
    id: 'event_5000',
    category: 'luck',
    title: 'เจ้าแห่งห้วงมิติเหตุการณ์',
    desc: 'เก็บอีเวนต์สะสมครบ 5,000 ครั้ง',
    icon: '👑',
    bonusPct: 28,
    check: (s) => (s.stats?.totalEventsClaimed || 0) >= 5000,
  },

  // --- บัฟโชคดีแจ็กพอต (Lucky Buff ×777) ---
  {
    id: 'lucky_1',
    category: 'luck',
    title: 'แจ็กพอตแห่งโชคชะตา',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) ครั้งแรก',
    icon: '🍀',
    bonusPct: 4,
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 1,
  },
  {
    id: 'lucky_10',
    category: 'luck',
    title: 'เทพแห่งโชคลาภ',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) สะสมครบ 10 ครั้ง',
    icon: '🎲',
    bonusPct: 8,
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 10,
  },
  {
    id: 'lucky_50',
    category: 'luck',
    title: 'ลูกรักแห่งโชคชะตา',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) สะสมครบ 50 ครั้ง',
    icon: '✨',
    bonusPct: 16,
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 50,
  },
  {
    id: 'lucky_100',
    category: 'luck',
    title: 'ผู้กำหนดดวงดาวนำโชค',
    desc: 'ได้รับบัฟโชคดี 🍀 (×777) สะสมครบ 100 ครั้ง',
    icon: '🌟',
    bonusPct: 25,
    check: (s) => (s.stats?.luckyJackpotCount || 0) >= 100,
  },

  // --- แจ็กพอตซ้อนแจ็กพอต (Super Jackpot) ---
  {
    id: 'super_jackpot',
    category: 'luck',
    title: 'แจ็กพอตซ้อนแจ็กพอต',
    desc: 'เก็บกล่อง 🎁 ได้รับสารอาหารก้อนโตขณะมีบัฟโชคดีทำงานอยู่',
    icon: '💥',
    bonusPct: 6,
    check: (s) => (s.stats?.superJackpotCount || (s.stats?.superJackpotClaimed ? 1 : 0)) >= 1,
  },
  {
    id: 'super_jackpot_5',
    category: 'luck',
    title: 'ดับเบิลแจ็กพอตช่ำชอง',
    desc: 'ได้รับแจ็กพอตซ้อนแจ็กพอตสะสมครบ 5 ครั้ง',
    icon: '🔥',
    bonusPct: 12,
    check: (s) => (s.stats?.superJackpotCount || (s.stats?.superJackpotClaimed ? 1 : 0)) >= 5,
  },
  {
    id: 'super_jackpot_10',
    category: 'luck',
    title: 'ดวงดาวบรรจบสองสาย',
    desc: 'ได้รับแจ็กพอตซ้อนแจ็กพอตสะสมครบ 10 ครั้ง',
    icon: '💫',
    bonusPct: 18,
    check: (s) => (s.stats?.superJackpotCount || (s.stats?.superJackpotClaimed ? 1 : 0)) >= 10,
  },
  {
    id: 'super_jackpot_25',
    category: 'luck',
    title: 'มหาโชคสองชั้นสะท้านภพ',
    desc: 'ได้รับแจ็กพอตซ้อนแจ็กพอตสะสมครบ 25 ครั้ง',
    icon: '👑',
    bonusPct: 26,
    check: (s) => (s.stats?.superJackpotCount || (s.stats?.superJackpotClaimed ? 1 : 0)) >= 25,
  },

  // --- อัปเกรดโชคชะตาในร้านหว่านใหม่ ---
  {
    id: 'event_bonus_25',
    category: 'luck',
    title: 'ผลตอบแทนงอกเงย',
    desc: 'อัปเกรดโบนัสอีเวนต์ (Event Value Booster) แตะเลเวล 25',
    icon: '🎁',
    bonusPct: 4,
    check: (s) => (s.prestige.eventBonusLevel || 0) >= 25,
  },
  {
    id: 'event_bonus_100',
    category: 'luck',
    title: 'มหาขุมทรัพย์ลอยฟ้า',
    desc: 'อัปเกรดโบนัสอีเวนต์ (Event Value Booster) แตะเลเวล 100',
    icon: '💰',
    bonusPct: 8,
    check: (s) => (s.prestige.eventBonusLevel || 0) >= 100,
  },
  {
    id: 'event_bonus_500',
    category: 'luck',
    title: 'ปรากฏการณ์พร่างพราย',
    desc: 'อัปเกรดโบนัสอีเวนต์ (Event Value Booster) แตะเลเวล 500',
    icon: '💎',
    bonusPct: 16,
    check: (s) => (s.prestige.eventBonusLevel || 0) >= 500,
  },
  {
    id: 'event_duration_max',
    category: 'luck',
    title: 'เวลาแห่งบัฟ',
    desc: 'อัปเกรดขยายระยะเวลาบัฟอีเวนต์แตะเลเวล 4 (สูงสุด)',
    icon: '⏳',
    bonusPct: 5,
    check: (s) => (s.prestige.eventDurationLevel || 0) >= 4,
  },
  {
    id: 'lucky_chance_max',
    category: 'luck',
    title: 'ทุ่งโคลเวอร์เบ่งบาน',
    desc: 'อัปเกรดโอกาสพบเจอโชคดีแตะเลเวล 8 (สูงสุด 1.0%)',
    icon: '🍀',
    bonusPct: 8,
    check: (s) => (s.prestige.luckyChanceLevel || 0) >= 8,
  },
  {
    id: 'lucky_magnitude_max',
    category: 'luck',
    title: 'โชคดีสิบเท่าทวีคูณ',
    desc: 'อัปเกรดโชคดีทวีคูณแตะเลเวล 9 (สูงสุด ทบตัวคูณโชคดี ×10)',
    icon: '🎲',
    bonusPct: 10,
    check: (s) => (s.prestige.luckyMagnitudeLevel || 0) >= 9,
  },

  // --- ละอองกลีบดอกไม้ดวงดาว (Astral Petals) - เลทเกมพิเศษ ให้ % สูง ---
  {
    id: 'astral_petal_1',
    category: 'luck',
    title: 'ละอองกลีบดวงดาราแรก',
    desc: 'เก็บหรือหลอมกลีบดอกไม้ดวงดาว (Astral Petals) ชิ้นแรกสำเร็จ',
    icon: '🌸',
    bonusPct: 10,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 1,
  },
  {
    id: 'astral_petal_10',
    category: 'luck',
    title: 'มาลัยดอกไม้แห่งฟากฟ้า',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมอย่างน้อย 10 กลีบ',
    icon: '💐',
    bonusPct: 15,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 10,
  },
  {
    id: 'astral_petal_50',
    category: 'luck',
    title: 'สวนบุปผาดวงดารานิรันดร์',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมครบ 50 กลีบ',
    icon: '🌺',
    bonusPct: 20,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 50,
  },
  {
    id: 'astral_petal_200',
    category: 'luck',
    title: 'ดาราจักรบุปผาพร่างพราว',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมครบ 200 กลีบ',
    icon: '🪐',
    bonusPct: 25,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 200,
  },
  {
    id: 'astral_petal_500',
    category: 'luck',
    title: 'มหาดวงดาราคอสมิกแห่งไกอา',
    desc: 'ครอบครองกลีบดอกไม้ดวงดาวสะสมครบ 500 กลีบ',
    icon: '✨',
    bonusPct: 30,
    check: (s) => (s.transcendence?.astralPetals || 0) >= 500,
  },
];
