import { AchievementDef } from '@/types/achievements';

export const PRESTIGE_ACHIEVEMENTS: AchievementDef[] = [
// ===== 🌌 หมวด 3: การหว่านใหม่ & ความเป็นนิรันดร์ (Prestige & Eternity) =====
  // --- จำนวนครั้งการหว่านใหม่ (Prestige Count) ---
  {
    id: 'prestige_1',
    category: 'prestige',
    title: 'วัฏจักรใหม่',
    desc: 'ทำการ Prestige (หว่านใหม่) ครั้งแรก',
    icon: '🔄',
    bonusPct: 2,
    check: (s) => (s.stats?.prestigeCount || 0) >= 1 || s.eternalSeeds > 0,
  },
  {
    id: 'prestige_5',
    category: 'prestige',
    title: 'การเดินทางที่ไม่สิ้นสุด',
    desc: 'Prestige หว่านใหม่สะสมครบ 5 ครั้ง',
    icon: '🔁',
    bonusPct: 4,
    check: (s) => (s.stats?.prestigeCount || 0) >= 5,
  },
  {
    id: 'prestige_20',
    category: 'prestige',
    title: 'ผู้ตรัสรู้ใต้ดิน',
    desc: 'Prestige หว่านใหม่สะสมครบ 20 ครั้ง',
    icon: '🧘',
    bonusPct: 8,
    check: (s) => (s.stats?.prestigeCount || 0) >= 20,
  },
  {
    id: 'prestige_50',
    category: 'prestige',
    title: 'วัฏสงสารนิรันดร์',
    desc: 'Prestige หว่านใหม่สะสมครบ 50 ครั้ง',
    icon: '♾️',
    bonusPct: 14,
    check: (s) => (s.stats?.prestigeCount || 0) >= 50,
  },
  {
    id: 'prestige_100',
    category: 'prestige',
    title: 'ผู้เจนจัดในสังสารวัฏ',
    desc: 'Prestige หว่านใหม่สะสมครบ 100 ครั้ง',
    icon: '🌌',
    bonusPct: 20,
    check: (s) => (s.stats?.prestigeCount || 0) >= 100,
  },
  {
    id: 'prestige_250',
    category: 'prestige',
    title: 'ปรมาจารย์แห่งการเกิดใหม่',
    desc: 'Prestige หว่านใหม่สะสมครบ 250 ครั้ง',
    icon: '👑',
    bonusPct: 30,
    check: (s) => (s.stats?.prestigeCount || 0) >= 250,
  },

  // --- เมล็ดพันธุ์นิรันดร์สะสม (Eternal Seeds) ---
  {
    id: 'seeds_10',
    category: 'prestige',
    title: 'เก็บเกี่ยวเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 10 เมล็ด',
    icon: '🌱',
    bonusPct: 1,
    check: (s) => s.eternalSeeds >= 10 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 10,
  },
  {
    id: 'seeds_1k',
    category: 'prestige',
    title: 'คลังเมล็ดดวงดาว',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000 เมล็ด',
    icon: '✨',
    bonusPct: 3,
    check: (s) => s.eternalSeeds >= 1000 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1000,
  },
  {
    id: 'seeds_100k',
    category: 'prestige',
    title: 'มหาเศรษฐีเมล็ดนิรันดร์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 100,000 เมล็ด',
    icon: '🌌',
    bonusPct: 6,
    check: (s) => s.eternalSeeds >= 100000 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 100000,
  },
  {
    id: 'seeds_1m',
    category: 'prestige',
    title: 'สวนแห่งเทพนิรันดร์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000,000 เมล็ด (1M)',
    icon: '🪐',
    bonusPct: 10,
    check: (s) => s.eternalSeeds >= 1e6 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e6,
  },
  {
    id: 'seeds_10m',
    category: 'prestige',
    title: 'ดาราจักรเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 10,000,000 เมล็ด (10M)',
    icon: '⭐',
    bonusPct: 14,
    check: (s) => s.eternalSeeds >= 1e7 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e7,
  },
  {
    id: 'seeds_50m',
    category: 'prestige',
    title: 'จอมราชันย์แห่งเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 50,000,000 เมล็ด (50M)',
    icon: '💎',
    bonusPct: 18,
    check: (s) => s.eternalSeeds >= 5e7 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 5e7,
  },
  {
    id: 'seeds_1b',
    category: 'prestige',
    title: 'ขุมทรัพย์เมล็ดพันล้าน',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000,000,000 เมล็ด (1B)',
    icon: '🏛️',
    bonusPct: 22,
    check: (s) => s.eternalSeeds >= 1e9 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e9,
  },
  {
    id: 'seeds_100b',
    category: 'prestige',
    title: 'เทพเจ้าแห่งการหว่านเมล็ด',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 100,000,000,000 เมล็ด (100B)',
    icon: '🌠',
    bonusPct: 26,
    check: (s) => s.eternalSeeds >= 1e11 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e11,
  },
  {
    id: 'seeds_1t',
    category: 'prestige',
    title: 'เมล็ดพันธุ์อนันต์มหาเอกภพ',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000,000,000,000 เมล็ด (1T)',
    icon: '👑',
    bonusPct: 30,
    check: (s) => s.eternalSeeds >= 1e12 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e12,
  },

  // --- ระบบอัตโนมัติ & อัปเกรดร้านค้าหว่านใหม่ ---
  {
    id: 'full_auto_unlocked',
    category: 'prestige',
    title: 'สายออโต้เต็มรูปแบบ',
    desc: 'ปลดล็อก ออโต้สรรพสิ่ง (Universal Automation) ในร้านค้าหว่านใหม่',
    icon: '🤖',
    bonusPct: 12,
    check: (s) => !!s.prestige.autoRoot,
  },
  {
    id: 'starter_culture_10',
    category: 'prestige',
    title: 'กลิ่นอายหัวเชื้อ',
    desc: 'อัปเกรดหัวเชื้อเริ่มต้น (Starter Culture) แตะเลเวล 10',
    icon: '🌱',
    bonusPct: 2,
    check: (s) => (s.prestige.starterLevel || 0) >= 10,
  },
  {
    id: 'starter_culture_25',
    category: 'prestige',
    title: 'รากฝอยพร้อมสรรพ',
    desc: 'อัปเกรดหัวเชื้อเริ่มต้น (Starter Culture) แตะเลเวล 25',
    icon: '🌿',
    bonusPct: 5,
    check: (s) => (s.prestige.starterLevel || 0) >= 25,
  },
  {
    id: 'starter_culture_50',
    category: 'prestige',
    title: 'จุดเริ่มต้นอันเกรียงไกร',
    desc: 'อัปเกรดหัวเชื้อเริ่มต้น (Starter Culture) เต็มเพดาน (Lv. 50)',
    icon: '🌲',
    bonusPct: 10,
    check: (s) => (s.prestige.starterLevel || 0) >= 50,
  },
  {
    id: 'golden_seed_max',
    category: 'prestige',
    title: 'เมล็ดทองคำเบ่งบาน',
    desc: 'อัปเกรดเมล็ดพันธุ์ทองคำ (Golden Seeds) แตะเลเวล 5',
    icon: '🏆',
    bonusPct: 3,
    check: (s) => (s.prestige.goldenLevel || 0) >= 5,
  },
  {
    id: 'golden_seed_25',
    category: 'prestige',
    title: 'ประกายทองคำเบ่งบาน',
    desc: 'อัปเกรดเมล็ดพันธุ์ทองคำ (Golden Seeds) แตะเลเวล 25',
    icon: '🏵️',
    bonusPct: 8,
    check: (s) => (s.prestige.goldenLevel || 0) >= 25,
  },
  {
    id: 'golden_seed_100',
    category: 'prestige',
    title: 'ทองคำแห่งผืนพิภพ',
    desc: 'อัปเกรดเมล็ดพันธุ์ทองคำ (Golden Seeds) แตะเลเวล 100',
    icon: '💰',
    bonusPct: 15,
    check: (s) => (s.prestige.goldenLevel || 0) >= 100,
  },
  {
    id: 'golden_seed_500',
    category: 'prestige',
    title: 'ทุ่งทองคำอร่ามจักรวาล',
    desc: 'อัปเกรดเมล็ดพันธุ์ทองคำ (Golden Seeds) แตะเลเวล 500',
    icon: '💎',
    bonusPct: 25,
    check: (s) => (s.prestige.goldenLevel || 0) >= 500,
  },
  {
    id: 'passive_rate_10',
    category: 'prestige',
    title: 'การดูดซึมไม่หยุดนิ่ง',
    desc: 'อัปเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 10',
    icon: '💧',
    bonusPct: 2,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 10,
  },
  {
    id: 'passive_rate_25',
    category: 'prestige',
    title: 'ชีพจรแห่งผืนดิน',
    desc: 'อัปเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 25',
    icon: '🌊',
    bonusPct: 6,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 25,
  },
  {
    id: 'passive_rate_50',
    category: 'prestige',
    title: 'กระแสรากต่อเนื่อง',
    desc: 'อัปเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 50',
    icon: '🌀',
    bonusPct: 10,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 50,
  },
  {
    id: 'passive_rate_100',
    category: 'prestige',
    title: 'กระแสชีพจรอนันต์',
    desc: 'อัปเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 100',
    icon: '⚡',
    bonusPct: 16,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 100,
  },
  {
    id: 'passive_rate_500',
    category: 'prestige',
    title: 'มหาพลังงานดูดซึมจักรวาล',
    desc: 'อัปเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 500',
    icon: '🌌',
    bonusPct: 24,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 500,
  },
  {
    id: 'lucky_duration_max',
    category: 'prestige',
    title: 'โชคชะตายืนยาว',
    desc: 'อัปเกรดระยะเวลาบัฟโชคดีครบ 20 วินาทีเต็ม (สูงสุด)',
    icon: '⏳',
    bonusPct: 10,
    check: (s) => (s.prestige.luckyDurationLevel || 0) >= 15,
  },
  {
    id: 'offline_cap_max',
    category: 'prestige',
    title: 'หลับใหลอย่างสงบใต้พสุธา',
    desc: 'ปลดล็อกเพดานเวลาออฟไลน์ครบ 72 ชั่วโมง (สูงสุด)',
    icon: '🌙',
    bonusPct: 15,
    check: (s) => (s.prestige.offlineCapLevel || 0) >= 2,
  },
];
