import { AchievementDef } from '@/types/achievements';

export const PRESTIGE_ACHIEVEMENTS: AchievementDef[] = [
// ===== 🌌 หมวด 3: การหว่านใหม่ & ความเป็นนิรันดร์ (Prestige & Eternity) =====
  {
    id: 'prestige_1',
    category: 'prestige',
    title: 'วัฏจักรใหม่',
    desc: 'ทำการ Prestige (หว่านใหม่) ครั้งแรก',
    icon: '🔄',
    bonusPct: 2,
    check: (s) => (s.stats?.prestigeCount || 0) >= 1 || s.eternalSeeds > 0,
  },
  {
    id: 'prestige_5',
    category: 'prestige',
    title: 'การเดินทางที่ไม่สิ้นสุด',
    desc: 'Prestige หว่านใหม่สะสมครบ 5 ครั้ง',
    icon: '🔁',
    bonusPct: 4,
    check: (s) => (s.stats?.prestigeCount || 0) >= 5,
  },
  {
    id: 'prestige_20',
    category: 'prestige',
    title: 'ผู้ตรัสรู้ใต้ดิน',
    desc: 'Prestige หว่านใหม่สะสมครบ 20 ครั้ง',
    icon: '🧘',
    bonusPct: 7,
    check: (s) => (s.stats?.prestigeCount || 0) >= 20,
  },
  {
    id: 'prestige_50',
    category: 'prestige',
    title: 'วัฏสงสารนิรันดร์',
    desc: 'Prestige หว่านใหม่สะสมครบ 50 ครั้ง',
    icon: '♾️',
    bonusPct: 10,
    check: (s) => (s.stats?.prestigeCount || 0) >= 50,
  },
  {
    id: 'seeds_10',
    category: 'prestige',
    title: 'เก็บเกี่ยวเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 10 เมล็ด',
    icon: '🌱',
    bonusPct: 1,
    check: (s) => s.eternalSeeds >= 10 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 10,
  },
  {
    id: 'seeds_1k',
    category: 'prestige',
    title: 'คลังเมล็ดดวงดาว',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000 เมล็ด',
    icon: '✨',
    bonusPct: 3,
    check: (s) => s.eternalSeeds >= 1000 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1000,
  },
  {
    id: 'seeds_100k',
    category: 'prestige',
    title: 'มหาเศรษฐีเมล็ดนิรันดร์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 100,000 เมล็ด',
    icon: '🌌',
    bonusPct: 5,
    check: (s) => s.eternalSeeds >= 100000 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 100000,
  },
  {
    id: 'seeds_1m',
    category: 'prestige',
    title: 'สวนแห่งเทพนิรันดร์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 1,000,000 เมล็ด (1M)',
    icon: '🪐',
    bonusPct: 8,
    check: (s) => s.eternalSeeds >= 1e6 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e6,
  },
  {
    id: 'seeds_10m',
    category: 'prestige',
    title: 'ดาราจักรเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 10,000,000 เมล็ด (10M)',
    icon: '👑',
    bonusPct: 10,
    check: (s) => s.eternalSeeds >= 1e7 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 1e7,
  },
  {
    id: 'seeds_50m',
    category: 'prestige',
    title: 'จอมราชันย์แห่งเมล็ดพันธุ์',
    desc: 'มีเมล็ดนิรันดร์สะสมอย่างน้อย 50,000,000 เมล็ด (50M)',
    icon: '💎',
    bonusPct: 10,
    check: (s) => s.eternalSeeds >= 5e7 || (s.stats?.totalSeedsEarnedLifetime || 0) >= 5e7,
  },
  {
    id: 'full_auto_unlocked',
    category: 'prestige',
    title: 'สายออโต้เต็มรูปแบบ',
    desc: 'ปลดล็อก ออโต้สรรพสิ่ง (Universal Automation) ครบจบในตัวเดียว',
    icon: '🤖',
    bonusPct: 8,
    check: (s) => !!s.prestige.autoRoot,
  },
  {
    id: 'golden_seed_max',
    category: 'prestige',
    title: 'เมล็ดทองคำเบ่งบาน',
    desc: 'อัพเกรดเมล็ดพันธุ์ทองคำ (Golden Seeds) แตะเลเวล 5',
    icon: '🏆',
    bonusPct: 7,
    check: (s) => (s.prestige.goldenLevel || 0) >= 5,
  },
  {
    id: 'lucky_duration_max',
    category: 'prestige',
    title: 'โชคชะตายืนยาว',
    desc: 'อัพเกรดระยะเวลาบัฟโชคดีครบ 20 วินาทีเต็ม (สูงสุด)',
    icon: '⏳',
    bonusPct: 10,
    check: (s) => (s.prestige.luckyDurationLevel || 0) >= 15,
  },
  {
    id: 'passive_rate_10',
    category: 'prestige',
    title: 'การดูดซึมไม่หยุดนิ่ง',
    desc: 'อัพเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 10',
    icon: '💧',
    bonusPct: 4,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 10,
  },
  {
    id: 'passive_rate_25',
    category: 'prestige',
    title: 'ชีพจรแห่งผืนดิน',
    desc: 'อัพเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 25',
    icon: '🌊',
    bonusPct: 7,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 25,
  },
  {
    id: 'passive_rate_50',
    category: 'prestige',
    title: 'กระแสรากต่อเนื่อง',
    desc: 'อัพเกรดเรทสารอาหารพื้นฐานถาวร (Passive Rate) ในร้านหว่านใหม่แตะเลเวล 50',
    icon: '🌊',
    bonusPct: 5,
    check: (s) => (s.prestige.passiveRateLevel || 0) >= 50,
  },
  {
    id: 'starter_culture_10',
    category: 'prestige',
    title: 'กลิ่นอายหัวเชื้อ',
    desc: 'อัพเกรดหัวเชื้อเริ่มต้น (Starter Culture) แตะเลเวล 10',
    icon: '🌱',
    bonusPct: 3,
    check: (s) => (s.prestige.starterLevel || 0) >= 10,
  },
  {
    id: 'starter_culture_25',
    category: 'prestige',
    title: 'รากฝอยพร้อมสรรพ',
    desc: 'อัพเกรดหัวเชื้อเริ่มต้น (Starter Culture) แตะเลเวล 25',
    icon: '🌿',
    bonusPct: 5,
    check: (s) => (s.prestige.starterLevel || 0) >= 25,
  },
  {
    id: 'golden_seed_25',
    category: 'prestige',
    title: 'ประกายทองคำเบ่งบาน',
    desc: 'อัพเกรดเมล็ดพันธุ์ทองคำ (Golden Seeds) แตะเลเวล 25',
    icon: '🏆',
    bonusPct: 5,
    check: (s) => (s.prestige.goldenLevel || 0) >= 25,
  },
];
