import { AchievementDef } from '@/types/achievements';
import { MODULE_DEFS } from '../modules';

export const ROOTS_ACHIEVEMENTS: AchievementDef[] = [
// ===== 🌿 หมวด 1: การเติบโต & การแผ่ขยายราก (Root Progression) =====
  {
    id: 'root_1',
    category: 'roots',
    title: 'ก้าวแรกสู่ดิน',
    desc: 'ซื้อรากเสริมรวม 1 ต้น',
    icon: '🌱',
    bonusPct: 1,
    check: (s) => s.totalOwned >= 1,
  },
  {
    id: 'root_50',
    category: 'roots',
    title: 'รากแตกแขนง',
    desc: 'มีรากเสริมรวมสะสม 50 ต้น',
    icon: '🌿',
    bonusPct: 2,
    check: (s) => s.totalOwned >= 50,
  },
  {
    id: 'root_250',
    category: 'roots',
    title: 'รากไม้พันปี',
    desc: 'มีรากเสริมรวมสะสม 250 ต้น',
    icon: '🌲',
    bonusPct: 3,
    check: (s) => s.totalOwned >= 250,
  },
  {
    id: 'root_1000',
    category: 'roots',
    title: 'พฤกษานิรันดร์',
    desc: 'มีรากเสริมรวมสะสม 1,000 ต้น',
    icon: '🌳',
    bonusPct: 5,
    check: (s) => s.totalOwned >= 1000,
  },
  {
    id: 'root_2500',
    category: 'roots',
    title: 'อาณาจักรราก',
    desc: 'มีรากเสริมรวมสะสม 2,500 ต้น',
    icon: '🌴',
    bonusPct: 6,
    check: (s) => s.totalOwned >= 2500,
  },
  {
    id: 'root_5000',
    category: 'roots',
    title: 'เครือข่ายรากไร้ขอบเขต',
    desc: 'มีรากเสริมรวมสะสม 5,000 ต้น',
    icon: '🎋',
    bonusPct: 7,
    check: (s) => s.totalOwned >= 5000,
  },
  {
    id: 'root_10000',
    category: 'roots',
    title: 'ผืนป่าครอบพิภพ',
    desc: 'มีรากเสริมรวมสะสม 10,000 ต้น',
    icon: '🪐',
    bonusPct: 8,
    check: (s) => s.totalOwned >= 10000,
  },
  {
    id: 'root_25000',
    category: 'roots',
    title: 'ผืนพิภพแห่งรากไม้',
    desc: 'มีรากเสริมรวมสะสม 25,000 ต้น',
    icon: '🌍',
    bonusPct: 9,
    check: (s) => s.totalOwned >= 25000,
  },
  {
    id: 'root_50000',
    category: 'roots',
    title: 'รากไม้โอบล้อมจักรวาล',
    desc: 'มีรากเสริมรวมสะสม 50,000 ต้น',
    icon: '🌌',
    bonusPct: 10,
    check: (s) => s.totalOwned >= 50000,
  },
  {
    id: 'fine_root_100',
    category: 'roots',
    title: 'ทุ่งรากฝอย',
    desc: 'มีรากฝอย (Fine Roots) สะสม 100 ต้น',
    icon: '🌾',
    bonusPct: 2,
    check: (s) => (s.owned['fine'] || 0) >= 100,
  },
  {
    id: 'fine_root_500',
    category: 'roots',
    title: 'พรมรากฝอยใต้ดิน',
    desc: 'มีรากฝอย (Fine Roots) สะสม 500 ต้น',
    icon: '🌱',
    bonusPct: 5,
    check: (s) => (s.owned['fine'] || 0) >= 500,
  },
  {
    id: 'fine_root_1000',
    category: 'roots',
    title: 'มหาสมุทรรากฝอย',
    desc: 'มีรากฝอย (Fine Roots) สะสม 1,000 ต้น',
    icon: '🌿',
    bonusPct: 10,
    check: (s) => (s.owned['fine'] || 0) >= 1000,
  },
  {
    id: 'all_modules_unlocked',
    category: 'roots',
    title: 'นักสะสมสายพันธุ์',
    desc: 'ปลดล็อกรากเสริมครบทุกชนิดในร้านค้า (21 สายพันธุ์)',
    icon: '📜',
    bonusPct: 10,
    check: (s) => MODULE_DEFS.every(d => (s.owned[d.id] || 0) >= 1),
  },
  {
    id: 'apex_root_1',
    category: 'roots',
    title: 'กำเนิดรากต้นไม้โลก',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) รากขั้นสูงสุดอย่างน้อย 1 ต้น',
    icon: '👑',
    bonusPct: 5,
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 1;
    },
  },
  {
    id: 'apex_root_10',
    category: 'roots',
    title: 'เสาค้ำจุนใต้พิภพ',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) อย่างน้อย 10 ต้น',
    icon: '💎',
    bonusPct: 8,
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 10;
    },
  },
  {
    id: 'apex_root_50',
    category: 'roots',
    title: 'จักรพรรดิแห่งพฤกษาอนันต์',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) อย่างน้อย 50 ต้น',
    icon: '🏛️',
    bonusPct: 10,
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 50;
    },
  },
  {
    id: 'apex_root_100',
    category: 'roots',
    title: 'อิกดราซิลค้ำจุนทุกมิติ',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) อย่างน้อย 100 ต้น',
    icon: '🌳',
    bonusPct: 15,
    check: (s) => {
      const last = MODULE_DEFS[MODULE_DEFS.length - 1];
      return (s.owned[last.id] || 0) >= 100;
    },
  },
  {
    id: 'upgrade_1',
    category: 'roots',
    title: 'อัพเกรดรากขั้นแรก',
    desc: 'อัพเกรดรากเสริมชนิดใดก็ได้แตะเลเวล 1',
    icon: '⬆️',
    bonusPct: 1,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 1),
  },
  {
    id: 'upgrade_5',
    category: 'roots',
    title: 'ก้าวกระโดด ×2',
    desc: 'อัพเกรดรากเสริมแตะเลเวล 5 (รับโบนัส ×2 Milestone)',
    icon: '⭐',
    bonusPct: 3,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 5),
  },
  {
    id: 'upgrade_10',
    category: 'roots',
    title: 'พลังแห่งวิวัฒนาการ',
    desc: 'อัพเกรดรากเสริมชนิดใดก็ได้แตะเลเวล 10',
    icon: '🌟',
    bonusPct: 7,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 10),
  },
  {
    id: 'echo_1',
    category: 'roots',
    title: 'สะท้อนรากแรก',
    desc: 'ซื้อสะท้อนราก (Echo) ครั้งแรก',
    icon: '✨',
    bonusPct: 2,
    check: (s) => Object.values(s.echoes || {}).some(lv => lv >= 1),
  },
  {
    id: 'echo_10',
    category: 'roots',
    title: 'สะท้อนประสานเสียง',
    desc: 'ซื้อสะท้อนรากสะสมรวม 10 ครั้ง',
    icon: '🔔',
    bonusPct: 5,
    check: (s) => Object.values(s.echoes || {}).reduce((a, b) => a + b, 0) >= 10,
  },
  {
    id: 'echo_all',
    category: 'roots',
    title: 'เสียงก้องกังวานทั้งผืนดิน',
    desc: 'ปลดล็อกสะท้อนราก (Echo) ครบทั้ง 21 สายพันธุ์',
    icon: '🎶',
    bonusPct: 10,
    check: (s) => MODULE_DEFS.every(d => (s.echoes?.[d.id] || 0) >= 1),
  },
  {
    id: 'synergy_1',
    category: 'roots',
    title: 'สายสัมพันธ์แรก',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) ชนิดใดก็ได้ 1 ชนิด',
    icon: '🌐',
    bonusPct: 3,
    check: (s) => Object.values(s.rootSynergies || {}).some(v => !!v),
  },
  {
    id: 'synergy_10',
    category: 'roots',
    title: 'โครงข่ายรากพิภพ',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) สะสมครบ 10 ชนิด',
    icon: '🕸️',
    bonusPct: 6,
    check: (s) => Object.values(s.rootSynergies || {}).filter(v => !!v).length >= 10,
  },
  {
    id: 'synergy_all',
    category: 'roots',
    title: 'เอกภาพแห่งผืนดิน',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) ครบทั้ง 21 สายพันธุ์',
    icon: '🌍',
    bonusPct: 10,
    check: (s) => MODULE_DEFS.every(d => !!s.rootSynergies?.[d.id]),
  },
];
