import { AchievementDef } from '@/types/achievements';
import { MODULE_DEFS } from '../modules';

export const ROOTS_ACHIEVEMENTS: AchievementDef[] = [
// ===== 🌿 หมวด 1: การเติบโต & การแผ่ขยายราก (Root Progression) =====
  // --- สะสมรากเสริมรวมตลอดกาล (Lifetime Roots) ---
  {
    id: 'root_1',
    category: 'roots',
    title: 'ก้าวแรกสู่ดิน',
    desc: 'ซื้อรากเสริมรวม 1 ต้น',
    icon: '🌱',
    bonusPct: 1,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 1,
  },
  {
    id: 'root_50',
    category: 'roots',
    title: 'รากแตกแขนง',
    desc: 'มีรากเสริมสะสมตลอดกาล 50 ต้น',
    icon: '🌿',
    bonusPct: 2,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 50,
  },
  {
    id: 'root_250',
    category: 'roots',
    title: 'รากไม้พันปี',
    desc: 'มีรากเสริมสะสมตลอดกาล 250 ต้น',
    icon: '🌲',
    bonusPct: 3,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 250,
  },
  {
    id: 'root_1000',
    category: 'roots',
    title: 'พฤกษานิรันดร์',
    desc: 'มีรากเสริมสะสมตลอดกาล 1,000 ต้น',
    icon: '🌳',
    bonusPct: 5,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 1000,
  },
  {
    id: 'root_2500',
    category: 'roots',
    title: 'อาณาจักรราก',
    desc: 'มีรากเสริมสะสมตลอดกาล 2,500 ต้น',
    icon: '🌴',
    bonusPct: 7,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 2500,
  },
  {
    id: 'root_5000',
    category: 'roots',
    title: 'เครือข่ายรากไร้ขอบเขต',
    desc: 'มีรากเสริมสะสมตลอดกาล 5,000 ต้น',
    icon: '🎋',
    bonusPct: 10,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 5000,
  },
  {
    id: 'root_10000',
    category: 'roots',
    title: 'ผืนป่าครอบพิภพ',
    desc: 'มีรากเสริมสะสมตลอดกาล 10,000 ต้น',
    icon: '🪐',
    bonusPct: 14,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 10000,
  },
  {
    id: 'root_25000',
    category: 'roots',
    title: 'ผืนพิภพแห่งรากไม้',
    desc: 'มีรากเสริมสะสมตลอดกาล 25,000 ต้น',
    icon: '🌍',
    bonusPct: 18,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 25000,
  },
  {
    id: 'root_50000',
    category: 'roots',
    title: 'รากไม้โอบล้อมจักรวาล',
    desc: 'มีรากเสริมสะสมตลอดกาล 50,000 ต้น',
    icon: '🌌',
    bonusPct: 24,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 50000,
  },
  {
    id: 'root_100000',
    category: 'roots',
    title: 'แสนรากประสานมิติ',
    desc: 'มีรากเสริมสะสมตลอดกาล 100,000 ต้น',
    icon: '👑',
    bonusPct: 30,
    check: (s) => (s.stats?.totalRootsPurchasedLifetime || s.totalOwned || 0) >= 100000,
  },

  // --- ความท้าทายดันรากรอบเดียว (Run Milestone) ---
  {
    id: 'run_roots_500',
    category: 'roots',
    title: 'มหาอาณาจักรรากเดี่ยว',
    desc: 'มีรากเสริมพร้อมกันในรอบเดียวแตะ 500 ต้น',
    icon: '🏰',
    bonusPct: 15,
    check: (s) => s.totalOwned >= 500,
  },

  // --- รากฝอย (Fine Roots) - ตันที่ 500 ต้น ---
  {
    id: 'fine_root_100',
    category: 'roots',
    title: 'ทุ่งรากฝอย',
    desc: 'มีรากฝอย (Fine Roots) สะสมในรอบ 100 ต้น',
    icon: '🌾',
    bonusPct: 2,
    check: (s) => (s.owned['fine'] || 0) >= 100,
  },
  {
    id: 'fine_root_250',
    category: 'roots',
    title: 'พรมรากฝอยใต้ดิน',
    desc: 'มีรากฝอย (Fine Roots) สะสมในรอบ 250 ต้น',
    icon: '🌱',
    bonusPct: 5,
    check: (s) => (s.owned['fine'] || 0) >= 250,
  },
  {
    id: 'fine_root_500',
    category: 'roots',
    title: 'มหาสมุทรรากฝอย',
    desc: 'มีรากฝอย (Fine Roots) สะสมในรอบ 500 ต้น',
    icon: '🌿',
    bonusPct: 10,
    check: (s) => (s.owned['fine'] || 0) >= 500,
  },
  {
    id: 'fine_root_1000',
    category: 'roots',
    title: 'มหาสมุทรรากฝอยชั้นสูง',
    desc: 'มีรากฝอย (Fine Roots) สะสมในรอบ 500 ต้นขึ้นไป',
    icon: '🌊',
    bonusPct: 10,
    check: (s) => (s.owned['fine'] || 0) >= 500,
  },

  // --- ปลดล็อกทุกสายพันธุ์ ---
  {
    id: 'all_modules_unlocked',
    category: 'roots',
    title: 'นักสะสมสายพันธุ์',
    desc: 'ปลดล็อกรากเสริมครบทุกชนิดในร้านค้า (20 สายพันธุ์)',
    icon: '📜',
    bonusPct: 12,
    check: (s) => MODULE_DEFS.every(d => (s.owned[d.id] || 0) >= 1),
  },

  // --- รากต้นไม้โลก (Yggdrasil Roots Lifetime) ---
  {
    id: 'apex_root_1',
    category: 'roots',
    title: 'กำเนิดรากต้นไม้โลก',
    desc: 'มีรากต้นไม้โลก (Yggdrasil) รากขั้นสูงสุดอย่างน้อย 1 ต้น',
    icon: '🌱',
    bonusPct: 5,
    check: (s) => (s.stats?.totalYggdrasilPurchasedLifetime || s.owned['yggdrasil'] || 0) >= 1,
  },
  {
    id: 'apex_root_10',
    category: 'roots',
    title: 'เสาค้ำจุนใต้พิภพ',
    desc: 'สะสมรากต้นไม้โลก (Yggdrasil) รวมตลอดกาล 10 ต้น',
    icon: '💎',
    bonusPct: 8,
    check: (s) => (s.stats?.totalYggdrasilPurchasedLifetime || s.owned['yggdrasil'] || 0) >= 10,
  },
  {
    id: 'apex_root_50',
    category: 'roots',
    title: 'จักรพรรดิแห่งพฤกษาอนันต์',
    desc: 'สะสมรากต้นไม้โลก (Yggdrasil) รวมตลอดกาล 50 ต้น',
    icon: '🏛️',
    bonusPct: 10,
    check: (s) => (s.stats?.totalYggdrasilPurchasedLifetime || s.owned['yggdrasil'] || 0) >= 50,
  },
  {
    id: 'apex_root_100',
    category: 'roots',
    title: 'อิกดราซิลค้ำจุนทุกมิติ',
    desc: 'สะสมรากต้นไม้โลก (Yggdrasil) รวมตลอดกาล 100 ต้น',
    icon: '🌳',
    bonusPct: 14,
    check: (s) => (s.stats?.totalYggdrasilPurchasedLifetime || s.owned['yggdrasil'] || 0) >= 100,
  },
  {
    id: 'apex_root_500',
    category: 'roots',
    title: 'พฤกษาอิกดราซิลร้อยภพ',
    desc: 'สะสมรากต้นไม้โลก (Yggdrasil) รวมตลอดกาล 500 ต้น',
    icon: '🪐',
    bonusPct: 18,
    check: (s) => (s.stats?.totalYggdrasilPurchasedLifetime || s.owned['yggdrasil'] || 0) >= 500,
  },
  {
    id: 'apex_root_1500',
    category: 'roots',
    title: 'พฤกษาอิกดราซิลไร้ขอบเขต',
    desc: 'สะสมรากต้นไม้โลก (Yggdrasil) รวมตลอดกาล 1,500 ต้น',
    icon: '🌌',
    bonusPct: 24,
    check: (s) => (s.stats?.totalYggdrasilPurchasedLifetime || s.owned['yggdrasil'] || 0) >= 1500,
  },
  {
    id: 'apex_root_5000',
    category: 'roots',
    title: 'มหาพฤกษาค้ำจุนจักรวาล',
    desc: 'สะสมรากต้นไม้โลก (Yggdrasil) รวมตลอดกาล 5,000 ต้น',
    icon: '👑',
    bonusPct: 30,
    check: (s) => (s.stats?.totalYggdrasilPurchasedLifetime || s.owned['yggdrasil'] || 0) >= 5000,
  },

  // --- การอัปเกรดราก (Root Upgrades) ---
  {
    id: 'upgrade_1',
    category: 'roots',
    title: 'อัปเกรดรากขั้นแรก',
    desc: 'อัปเกรดรากเสริมชนิดใดก็ได้แตะเลเวล 1',
    icon: '⬆️',
    bonusPct: 1,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 1),
  },
  {
    id: 'upgrade_5',
    category: 'roots',
    title: 'ก้าวกระโดด ×2',
    desc: 'อัปเกรดรากเสริมแตะเลเวล 5 (รับโบนัส ×2 Milestone)',
    icon: '⭐',
    bonusPct: 4,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 5),
  },
  {
    id: 'upgrade_10',
    category: 'roots',
    title: 'พลังแห่งวิวัฒนาการ',
    desc: 'อัปเกรดรากเสริมชนิดใดก็ได้แตะเลเวล 10',
    icon: '🌟',
    bonusPct: 8,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 10),
  },
  {
    id: 'upgrade_25',
    category: 'roots',
    title: 'การเติบโตเหนือขีดจำกัด',
    desc: 'อัปเกรดรากเสริมชนิดใดก็ได้แตะเลเวล 25',
    icon: '✨',
    bonusPct: 15,
    check: (s) => Object.values(s.rootUpgrades || {}).some(lv => lv >= 25),
  },

  // --- สะท้อนราก (Echoes) ---
  {
    id: 'echo_1',
    category: 'roots',
    title: 'สะท้อนรากแรก',
    desc: 'ซื้อสะท้อนราก (Echo) ครั้งแรก',
    icon: '✨',
    bonusPct: 2,
    check: (s) => Object.values(s.echoes || {}).some(lv => lv >= 1),
  },
  {
    id: 'echo_10',
    category: 'roots',
    title: 'สะท้อนประสานเสียง',
    desc: 'ซื้อสะท้อนรากสะสมรวม 10 ครั้ง',
    icon: '🔔',
    bonusPct: 6,
    check: (s) => Object.values(s.echoes || {}).reduce((a, b) => a + b, 0) >= 10,
  },
  {
    id: 'echo_all',
    category: 'roots',
    title: 'เสียงก้องกังวานทั้งผืนดิน',
    desc: 'ปลดล็อกสะท้อนราก (Echo) ครบทั้ง 20 สายพันธุ์',
    icon: '🎶',
    bonusPct: 15,
    check: (s) => MODULE_DEFS.every(d => (s.echoes?.[d.id] || 0) >= 1),
  },
  {
    id: 'echo_50',
    category: 'roots',
    title: 'ท่วงทำนองแห่งปฐพี',
    desc: 'ซื้อสะท้อนรากสะสมรวม 50 ครั้ง',
    icon: '🎼',
    bonusPct: 22,
    check: (s) => Object.values(s.echoes || {}).reduce((a, b) => a + b, 0) >= 50,
  },

  // --- เครือข่ายราก (Synergies) ---
  {
    id: 'synergy_1',
    category: 'roots',
    title: 'สายสัมพันธ์แรก',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) ชนิดใดก็ได้ 1 ชนิด',
    icon: '🌐',
    bonusPct: 2,
    check: (s) => Object.values(s.rootSynergies || {}).some(v => !!v),
  },
  {
    id: 'synergy_10',
    category: 'roots',
    title: 'โครงข่ายรากพิภพ',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) สะสมครบ 10 ชนิด',
    icon: '🕸️',
    bonusPct: 8,
    check: (s) => Object.values(s.rootSynergies || {}).filter(v => !!v).length >= 10,
  },
  {
    id: 'synergy_all',
    category: 'roots',
    title: 'เอกภาพแห่งผืนดิน',
    desc: 'เปิดใช้งานเครือข่ายราก (Synergy) ครบทั้ง 20 สายพันธุ์',
    icon: '🌍',
    bonusPct: 18,
    check: (s) => MODULE_DEFS.every(d => !!s.rootSynergies?.[d.id]),
  },
];
