import { AchievementDef } from '@/types/achievements';
import { GameState } from '@/types/game';

function getSaveAgeSeconds(s: GameState): number {
  if (s.saveCreatedAt) {
    return Math.max(
      (Date.now() - s.saveCreatedAt) / 1000,
      (s.totalPlayTimeSeconds || 0) + (s.totalOfflineTimeSeconds || 0)
    );
  }
  return (s.totalPlayTimeSeconds || 0) + (s.totalOfflineTimeSeconds || 0);
}

export const TIME_ACHIEVEMENTS: AchievementDef[] = [
  // ===== 1. 💤 หมวดเวลาออฟไลน์สะสม (Total Offline Time) =====
  {
    id: 'offline_1h',
    category: 'time',
    title: 'กลับมาดูแล',
    desc: 'เก็บผลผลิตออฟไลน์ (Offline Gain) ที่หายไปเกิน 1 ชั่วโมง',
    icon: '🏡',
    bonusPct: 1,
    check: (s) => (s.stats?.maxOfflineTimeSeconds || 0) >= 3600 || (s.totalOfflineTimeSeconds || 0) >= 3600,
  },
  {
    id: 'offline_4h',
    category: 'time',
    title: 'พักสายตาสักครู่',
    desc: 'เวลาออฟไลน์สะสมครบ 4 ชั่วโมง',
    icon: '🌿',
    bonusPct: 2,
    check: (s) => (s.totalOfflineTimeSeconds || 0) >= 14400 || (s.stats?.maxOfflineTimeSeconds || 0) >= 14400,
  },
  {
    id: 'offline_8h',
    category: 'time',
    title: 'นิทราราตรี',
    desc: 'เวลาออฟไลน์สะสมครบ 8 ชั่วโมง',
    icon: '🌙',
    bonusPct: 4,
    check: (s) => (s.totalOfflineTimeSeconds || 0) >= 28800 || (s.stats?.maxOfflineTimeSeconds || 0) >= 28800,
  },
  {
    id: 'offline_12h',
    category: 'time',
    title: 'ภวังค์แห่งแมกไม้',
    desc: 'เวลาออฟไลน์สะสมครบ 12 ชั่วโมง',
    icon: '🏡',
    bonusPct: 6,
    check: (s) => (s.totalOfflineTimeSeconds || 0) >= 43200 || (s.stats?.maxOfflineTimeSeconds || 0) >= 43200,
  },
  {
    id: 'offline_24h',
    category: 'time',
    title: 'การหลับใหลอันยาวนาน',
    desc: 'เวลาออฟไลน์สะสมครบ 24 ชั่วโมง',
    icon: '💤',
    bonusPct: 10,
    check: (s) => (s.totalOfflineTimeSeconds || 0) >= 86400 || (s.stats?.maxOfflineTimeSeconds || 0) >= 86400,
  },
  {
    id: 'offline_48h',
    category: 'time',
    title: 'ดำดิ่งใต้ไอหมอก',
    desc: 'เวลาออฟไลน์สะสมครบ 48 ชั่วโมง (2 วัน)',
    icon: '🪨',
    bonusPct: 16,
    check: (s) => (s.totalOfflineTimeSeconds || 0) >= 172800 || (s.stats?.maxOfflineTimeSeconds || 0) >= 172800,
  },

  // ===== 2. 🟢 หมวดเวลาออนไลน์สะสม (Active / Online Playtime) =====
  {
    id: 'playtime_10m',
    category: 'time',
    title: 'รดน้ำอย่างใจเย็น',
    desc: 'เวลาออนไลน์สะสมครบ 10 นาที',
    icon: '⏱️',
    bonusPct: 1,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 600,
  },
  {
    id: 'playtime_1h',
    category: 'time',
    title: 'ผู้เฝ้ามองราก',
    desc: 'เวลาออนไลน์สะสมครบ 1 ชั่วโมง',
    icon: '⏳',
    bonusPct: 2,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 3600,
  },
  {
    id: 'online_2h',
    category: 'time',
    title: 'ผู้เริ่มหยั่งราก',
    desc: 'เวลาออนไลน์สะสมครบ 2 ชั่วโมง',
    icon: '⏱️',
    bonusPct: 2,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 7200,
  },
  {
    id: 'online_4h',
    category: 'time',
    title: 'ผู้หมั่นรดน้ำ',
    desc: 'เวลาออนไลน์สะสมครบ 4 ชั่วโมง',
    icon: '🌱',
    bonusPct: 4,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 14400,
  },
  {
    id: 'online_6h',
    category: 'time',
    title: 'ผู้ดูแลผืนดิน',
    desc: 'เวลาออนไลน์สะสมครบ 6 ชั่วโมง',
    icon: '🪴',
    bonusPct: 6,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 21600,
  },
  {
    id: 'online_8h',
    category: 'time',
    title: 'ผู้เฝ้ามองลำต้น',
    desc: 'เวลาออนไลน์สะสมครบ 8 ชั่วโมง',
    icon: '⏳',
    bonusPct: 8,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 28800,
  },
  {
    id: 'playtime_12h',
    category: 'time',
    title: 'ป่าไม้ตลอดกาล',
    desc: 'เวลาออนไลน์สะสมครบ 12 ชั่วโมง',
    icon: '🏆',
    bonusPct: 10,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 43200,
  },
  {
    id: 'online_16h',
    category: 'time',
    title: 'รากหยั่งลึกไม่ไหวติง',
    desc: 'เวลาออนไลน์สะสมครบ 16 ชั่วโมง',
    icon: '🛡️',
    bonusPct: 12,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 57600,
  },
  {
    id: 'playtime_24h',
    category: 'time',
    title: 'ผู้พิทักษ์ผืนป่า',
    desc: 'เวลาออนไลน์สะสมครบ 24 ชั่วโมง (1 วัน)',
    icon: '🌲',
    bonusPct: 15,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 86400,
  },
  {
    id: 'online_36h',
    category: 'time',
    title: 'เจตนารมณ์ไม่สั่นคลอน',
    desc: 'เวลาออนไลน์สะสมครบ 36 ชั่วโมง',
    icon: '🪵',
    bonusPct: 17,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 129600,
  },
  {
    id: 'online_48h',
    category: 'time',
    title: 'ศิลาแห่งกาลเวลา',
    desc: 'เวลาออนไลน์สะสมครบ 48 ชั่วโมง (2 วัน)',
    icon: '⛰️',
    bonusPct: 20,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 172800,
  },
  {
    id: 'online_60h',
    category: 'time',
    title: 'ลมหายใจแห่งผืนดิน',
    desc: 'เวลาออนไลน์สะสมครบ 60 ชั่วโมง',
    icon: '🌪️',
    bonusPct: 22,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 216000,
  },
  {
    id: 'online_72h',
    category: 'time',
    title: 'เจ้าแห่งพฤกษาสามวัน',
    desc: 'เวลาออนไลน์สะสมครบ 3 วัน (72 ชั่วโมง)',
    icon: '👑',
    bonusPct: 24,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 259200,
  },
  {
    id: 'online_96h',
    category: 'time',
    title: 'ผู้กลืนกินวันเวลา',
    desc: 'เวลาออนไลน์สะสมครบ 4 วัน (96 ชั่วโมง)',
    icon: '🔮',
    bonusPct: 26,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 345600,
  },
  {
    id: 'online_120h',
    category: 'time',
    title: 'ร่มเงาอันไร้สิ้นสุด',
    desc: 'เวลาออนไลน์สะสมครบ 5 วัน (120 ชั่วโมง)',
    icon: '🌌',
    bonusPct: 27,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 432000,
  },
  {
    id: 'online_144h',
    category: 'time',
    title: 'ตำนานใต้พิภพที่ยังมีชีวิต',
    desc: 'เวลาออนไลน์สะสมครบ 6 วัน (144 ชั่วโมง)',
    icon: '✨',
    bonusPct: 28,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 518400,
  },
  {
    id: 'online_168h',
    category: 'time',
    title: 'สหัสวรรษแห่งไกอา',
    desc: 'เวลาออนไลน์สะสมครบ 7 วันเต็ม (168 ชั่วโมง)!',
    icon: '🌟',
    bonusPct: 30,
    check: (s) => (s.totalPlayTimeSeconds || 0) >= 604800,
  },

  // ===== 3. ⏳ หมวดเวลาเล่นรวมตั้งแต่เริ่ม (Total Journey Age) =====
  {
    id: 'age_4h',
    category: 'time',
    title: 'ต้นกล้าแรกแย้ม',
    desc: 'เริ่มต้นการเดินทางครบ 4 ชั่วโมง',
    icon: '🌰',
    bonusPct: 1,
    check: (s) => getSaveAgeSeconds(s) >= 14400,
  },
  {
    id: 'age_8h',
    category: 'time',
    title: 'กิ่งก้านผลิใบ',
    desc: 'เริ่มต้นการเดินทางครบ 8 ชั่วโมง',
    icon: '🍃',
    bonusPct: 2,
    check: (s) => getSaveAgeSeconds(s) >= 28800,
  },
  {
    id: 'age_12h',
    category: 'time',
    title: 'รอยเท้าก้าวแรก',
    desc: 'เริ่มต้นการเดินทางครบ 12 ชั่วโมง',
    icon: '👣',
    bonusPct: 3,
    check: (s) => getSaveAgeSeconds(s) >= 43200,
  },
  {
    id: 'age_16h',
    category: 'time',
    title: 'ผืนดินที่คุ้นเคย',
    desc: 'เริ่มต้นการเดินทางครบ 16 ชั่วโมง',
    icon: '🌾',
    bonusPct: 4,
    check: (s) => getSaveAgeSeconds(s) >= 57600,
  },
  {
    id: 'age_20h',
    category: 'time',
    title: 'สายธารแห่งชีวิต',
    desc: 'เริ่มต้นการเดินทางครบ 20 ชั่วโมง',
    icon: '💧',
    bonusPct: 5,
    check: (s) => getSaveAgeSeconds(s) >= 72000,
  },
  {
    id: 'age_24h',
    category: 'time',
    title: 'ก้าวพ้นวันแรก',
    desc: 'เริ่มต้นการเดินทางครบ 1 วัน (24 ชั่วโมง)',
    icon: '🌅',
    bonusPct: 7,
    check: (s) => getSaveAgeSeconds(s) >= 86400,
  },
  {
    id: 'age_36h',
    category: 'time',
    title: 'บันทึกความทรงจำ',
    desc: 'เริ่มต้นการเดินทางครบ 36 ชั่วโมง',
    icon: '📜',
    bonusPct: 9,
    check: (s) => getSaveAgeSeconds(s) >= 129600,
  },
  {
    id: 'age_48h',
    category: 'time',
    title: 'รากฐานมั่นคง',
    desc: 'เริ่มต้นการเดินทางครบ 2 วัน (48 ชั่วโมง)',
    icon: '🏛️',
    bonusPct: 12,
    check: (s) => getSaveAgeSeconds(s) >= 172800,
  },
  {
    id: 'age_72h',
    category: 'time',
    title: 'วันวานอันงดงาม',
    desc: 'เริ่มต้นการเดินทางครบ 3 วัน (72 ชั่วโมง)',
    icon: '🍂',
    bonusPct: 16,
    check: (s) => getSaveAgeSeconds(s) >= 259200,
  },
  {
    id: 'age_96h',
    category: 'time',
    title: 'เส้นทางแห่งพฤกษชาติ',
    desc: 'เริ่มต้นการเดินทางครบ 4 วัน (96 ชั่วโมง)',
    icon: '🗺️',
    bonusPct: 20,
    check: (s) => getSaveAgeSeconds(s) >= 345600,
  },
  {
    id: 'age_120h',
    category: 'time',
    title: 'อนุสรณ์สถานดึกดำบรรพ์',
    desc: 'เริ่มต้นการเดินทางครบ 5 วัน (120 ชั่วโมง)',
    icon: '🗿',
    bonusPct: 23,
    check: (s) => getSaveAgeSeconds(s) >= 432000,
  },
  {
    id: 'age_144h',
    category: 'time',
    title: 'วงปีที่ไม่อาจลบเลือน',
    desc: 'เริ่มต้นการเดินทางครบ 6 วัน (144 ชั่วโมง)',
    icon: '🪐',
    bonusPct: 26,
    check: (s) => getSaveAgeSeconds(s) >= 518400,
  },
  {
    id: 'age_168h',
    category: 'time',
    title: 'สัปดาห์แรกแห่งปาฏิหาริย์',
    desc: 'เริ่มต้นการเดินทางครบ 1 สัปดาห์เต็ม (7 วัน)!',
    icon: '🏆',
    bonusPct: 30,
    check: (s) => getSaveAgeSeconds(s) >= 604800,
  },

  // ===== 4. ⏱️ หมวดเวลาต่อรอบ (Current Run Duration) =====
  {
    id: 'run_30m',
    category: 'time',
    title: 'ปลูกแช่ครึ่งชั่วโมง',
    desc: 'ฟาร์มในรอบปัจจุบันต่อเนื่องครบ 30 นาที',
    icon: '☕',
    bonusPct: 2,
    check: (s) => (s.runPlayTimeSeconds || 0) >= 1800,
  },
  {
    id: 'run_1h',
    category: 'time',
    title: 'สายแช่ตัวจริง',
    desc: 'ฟาร์มในรอบปัจจุบันต่อเนื่องครบ 1 ชั่วโมง',
    icon: '🍵',
    bonusPct: 4,
    check: (s) => (s.runPlayTimeSeconds || 0) >= 3600,
  },
  {
    id: 'run_2h',
    category: 'time',
    title: 'ต้นไม้ไม่ยอมหว่าน',
    desc: 'ฟาร์มในรอบปัจจุบันต่อเนื่องครบ 2 ชั่วโมง',
    icon: '🌲',
    bonusPct: 6,
    check: (s) => (s.runPlayTimeSeconds || 0) >= 7200,
  },
  {
    id: 'run_3h',
    category: 'time',
    title: 'ปล่อยใจใต้เงาไม้',
    desc: 'ฟาร์มในรอบปัจจุบันต่อเนื่องครบ 3 ชั่วโมง',
    icon: '🕊️',
    bonusPct: 8,
    check: (s) => (s.runPlayTimeSeconds || 0) >= 10800,
  },
  {
    id: 'run_4h',
    category: 'time',
    title: 'ดื่มด่ำรสชาติเซน',
    desc: 'ฟาร์มในรอบปัจจุบันต่อเนื่องครบ 4 ชั่วโมง',
    icon: '🧘',
    bonusPct: 11,
    check: (s) => (s.runPlayTimeSeconds || 0) >= 14400,
  },
  {
    id: 'run_6h',
    category: 'time',
    title: 'รากฝังแน่นไม่คิดรีเซ็ต',
    desc: 'ฟาร์มในรอบปัจจุบันต่อเนื่องครบ 6 ชั่วโมง',
    icon: '🏰',
    bonusPct: 15,
    check: (s) => (s.runPlayTimeSeconds || 0) >= 21600,
  },
  {
    id: 'run_8h',
    category: 'time',
    title: 'ฟาร์มข้ามกะมาราธอน',
    desc: 'ฟาร์มในรอบปัจจุบันต่อเนื่องครบ 8 ชั่วโมง!',
    icon: '⚡',
    bonusPct: 20,
    check: (s) => (s.runPlayTimeSeconds || 0) >= 28800,
  },
];
